/**
 *
 *  Harvests.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/BaseBuilder.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <iostream>
#include <json/json.h>
#include <memory>
#include <stdint.h>
#include <string>
#include <string_view>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <tuple>
#include <vector>

namespace drogon {
namespace orm {
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
} // namespace orm
} // namespace drogon
namespace drogon_model {
namespace los_css_drogon {

class Harvests {
public:
  struct Cols {
    static const std::string _id;
    static const std::string _area_id;
    static const std::string _harvest_date;
    static const std::string _batch_number;
    static const std::string _output_quantity;
    static const std::string _quality_level;
    static const std::string _responsible_person;
    static const std::string _harvest_method;
    static const std::string _storage_location;
    static const std::string _inspection_status;
    static const std::string _remarks;
    static const std::string _created_at;
    static const std::string _updated_at;
  };

  static const int primaryKeyNumber;
  static const std::string tableName;
  static const bool hasPrimaryKey;
  static const std::string primaryKeyName;
  using PrimaryKeyType = int32_t;
  const PrimaryKeyType &getPrimaryKey() const;

  /**
   * @brief constructor
   * @param r One row of records in the SQL query result.
   * @param indexOffset Set the offset to -1 to access all columns by column names,
   * otherwise access all columns by offsets.
   * @note If the SQL is not a style of 'select * from table_name ...' (select all
   * columns by an asterisk), please set the offset to -1.
   */
  explicit Harvests(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

  /**
   * @brief constructor
   * @param pJson The json object to construct a new instance.
   */
  explicit Harvests(const Json::Value &pJson) noexcept(false);

  /**
   * @brief constructor
   * @param pJson The json object to construct a new instance.
   * @param pMasqueradingVector The aliases of table columns.
   */
  Harvests(const Json::Value &pJson,
           const std::vector<std::string> &pMasqueradingVector) noexcept(false);

  Harvests() = default;

  void updateByJson(const Json::Value &pJson) noexcept(false);
  void updateByMasqueradedJson(const Json::Value &pJson,
                               const std::vector<std::string> &pMasqueradingVector) noexcept(false);
  static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
  static bool validateMasqueradedJsonForCreation(
      const Json::Value &, const std::vector<std::string> &pMasqueradingVector, std::string &err);
  static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
  static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err);
  static bool validJsonOfField(size_t index, const std::string &fieldName, const Json::Value &pJson,
                               std::string &err, bool isForCreation);

  /**  For column id  */
  /// Get the value of the column id, returns the default value if the column is null
  const int32_t &getValueOfId() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<int32_t> &getId() const noexcept;
  /// Set the value of the column id
  void setId(const int32_t &pId) noexcept;

  /**  For column area_id  */
  /// Get the value of the column area_id, returns the default value if the column is null
  const int32_t &getValueOfAreaId() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<int32_t> &getAreaId() const noexcept;
  /// Set the value of the column area_id
  void setAreaId(const int32_t &pAreaId) noexcept;

  /**  For column harvest_date  */
  /// Get the value of the column harvest_date, returns the default value if the column is null
  const ::trantor::Date &getValueOfHarvestDate() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getHarvestDate() const noexcept;
  /// Set the value of the column harvest_date
  void setHarvestDate(const ::trantor::Date &pHarvestDate) noexcept;

  /**  For column batch_number  */
  /// Get the value of the column batch_number, returns the default value if the column is null
  const std::string &getValueOfBatchNumber() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getBatchNumber() const noexcept;
  /// Set the value of the column batch_number
  void setBatchNumber(const std::string &pBatchNumber) noexcept;
  void setBatchNumber(std::string &&pBatchNumber) noexcept;

  /**  For column output_quantity  */
  /// Get the value of the column output_quantity, returns the default value if the column is null
  const std::string &getValueOfOutputQuantity() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getOutputQuantity() const noexcept;
  /// Set the value of the column output_quantity
  void setOutputQuantity(const std::string &pOutputQuantity) noexcept;
  void setOutputQuantity(std::string &&pOutputQuantity) noexcept;

  /**  For column quality_level  */
  /// Get the value of the column quality_level, returns the default value if the column is null
  const std::string &getValueOfQualityLevel() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getQualityLevel() const noexcept;
  /// Set the value of the column quality_level
  void setQualityLevel(const std::string &pQualityLevel) noexcept;
  void setQualityLevel(std::string &&pQualityLevel) noexcept;

  /**  For column responsible_person  */
  /// Get the value of the column responsible_person, returns the default value if the column is
  /// null
  const std::string &getValueOfResponsiblePerson() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getResponsiblePerson() const noexcept;
  /// Set the value of the column responsible_person
  void setResponsiblePerson(const std::string &pResponsiblePerson) noexcept;
  void setResponsiblePerson(std::string &&pResponsiblePerson) noexcept;

  /**  For column harvest_method  */
  /// Get the value of the column harvest_method, returns the default value if the column is null
  const std::string &getValueOfHarvestMethod() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getHarvestMethod() const noexcept;
  /// Set the value of the column harvest_method
  void setHarvestMethod(const std::string &pHarvestMethod) noexcept;
  void setHarvestMethod(std::string &&pHarvestMethod) noexcept;

  /**  For column storage_location  */
  /// Get the value of the column storage_location, returns the default value if the column is null
  const std::string &getValueOfStorageLocation() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getStorageLocation() const noexcept;
  /// Set the value of the column storage_location
  void setStorageLocation(const std::string &pStorageLocation) noexcept;
  void setStorageLocation(std::string &&pStorageLocation) noexcept;

  /**  For column inspection_status  */
  /// Get the value of the column inspection_status, returns the default value if the column is null
  const std::string &getValueOfInspectionStatus() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getInspectionStatus() const noexcept;
  /// Set the value of the column inspection_status
  void setInspectionStatus(const std::string &pInspectionStatus) noexcept;
  void setInspectionStatus(std::string &&pInspectionStatus) noexcept;

  /**  For column remarks  */
  /// Get the value of the column remarks, returns the default value if the column is null
  const std::string &getValueOfRemarks() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getRemarks() const noexcept;
  /// Set the value of the column remarks
  void setRemarks(const std::string &pRemarks) noexcept;
  void setRemarks(std::string &&pRemarks) noexcept;
  void setRemarksToNull() noexcept;

  /**  For column created_at  */
  /// Get the value of the column created_at, returns the default value if the column is null
  const ::trantor::Date &getValueOfCreatedAt() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
  /// Set the value of the column created_at
  void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;

  /**  For column updated_at  */
  /// Get the value of the column updated_at, returns the default value if the column is null
  const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
  /// Set the value of the column updated_at
  void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;


  static size_t getColumnNumber() noexcept { return 13; }
  static const std::string &getColumnName(size_t index) noexcept(false);

  Json::Value toJson() const;
  Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
  /// Relationship interfaces
private:
  friend drogon::orm::Mapper<Harvests>;
  friend drogon::orm::BaseBuilder<Harvests, true, true>;
  friend drogon::orm::BaseBuilder<Harvests, true, false>;
  friend drogon::orm::BaseBuilder<Harvests, false, true>;
  friend drogon::orm::BaseBuilder<Harvests, false, false>;
#ifdef __cpp_impl_coroutine
  friend drogon::orm::CoroMapper<Harvests>;
#endif
  static const std::vector<std::string> &insertColumns() noexcept;
  void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
  const std::vector<std::string> updateColumns() const;
  void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
  /// For mysql or sqlite3
  void updateId(const uint64_t id);
  std::shared_ptr<int32_t> id_;
  std::shared_ptr<int32_t> areaId_;
  std::shared_ptr<::trantor::Date> harvestDate_;
  std::shared_ptr<std::string> batchNumber_;
  std::shared_ptr<std::string> outputQuantity_;
  std::shared_ptr<std::string> qualityLevel_;
  std::shared_ptr<std::string> responsiblePerson_;
  std::shared_ptr<std::string> harvestMethod_;
  std::shared_ptr<std::string> storageLocation_;
  std::shared_ptr<std::string> inspectionStatus_;
  std::shared_ptr<std::string> remarks_;
  std::shared_ptr<::trantor::Date> createdAt_;
  std::shared_ptr<::trantor::Date> updatedAt_;
  struct MetaData {
    const std::string colName_;
    const std::string colType_;
    const std::string colDatabaseType_;
    const ssize_t colLength_;
    const bool isAutoVal_;
    const bool isPrimaryKey_;
    const bool notNull_;
  };
  static const std::vector<MetaData> metaData_;
  bool dirtyFlag_[13] = {false};

public:
  static const std::string &sqlForFindingByPrimaryKey() {
    static const std::string sql = "select * from " + tableName + " where id = $1";
    return sql;
  }

  static const std::string &sqlForDeletingByPrimaryKey() {
    static const std::string sql = "delete from " + tableName + " where id = $1";
    return sql;
  }
  std::string sqlForInserting(bool &needSelection) const {
    std::string sql = "insert into " + tableName + " (";
    size_t parametersCount = 0;
    needSelection = false;
    sql += "id,";
    ++parametersCount;
    if (dirtyFlag_[1]) {
      sql += "area_id,";
      ++parametersCount;
    }
    if (dirtyFlag_[2]) {
      sql += "harvest_date,";
      ++parametersCount;
    }
    if (dirtyFlag_[3]) {
      sql += "batch_number,";
      ++parametersCount;
    }
    if (dirtyFlag_[4]) {
      sql += "output_quantity,";
      ++parametersCount;
    }
    if (dirtyFlag_[5]) {
      sql += "quality_level,";
      ++parametersCount;
    }
    if (dirtyFlag_[6]) {
      sql += "responsible_person,";
      ++parametersCount;
    }
    if (dirtyFlag_[7]) {
      sql += "harvest_method,";
      ++parametersCount;
    }
    if (dirtyFlag_[8]) {
      sql += "storage_location,";
      ++parametersCount;
    }
    if (dirtyFlag_[9]) {
      sql += "inspection_status,";
      ++parametersCount;
    }
    if (dirtyFlag_[10]) {
      sql += "remarks,";
      ++parametersCount;
    }
    sql += "created_at,";
    ++parametersCount;
    if (!dirtyFlag_[11]) {
      needSelection = true;
    }
    sql += "updated_at,";
    ++parametersCount;
    if (!dirtyFlag_[12]) {
      needSelection = true;
    }
    needSelection = true;
    if (parametersCount > 0) {
      sql[sql.length() - 1] = ')';
      sql += " values (";
    } else
      sql += ") values (";

    int placeholder = 1;
    char placeholderStr[64];
    size_t n = 0;
    sql += "default,";
    if (dirtyFlag_[1]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[2]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[3]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[4]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[5]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[6]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[7]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[8]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[9]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[10]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[11]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    } else {
      sql += "default,";
    }
    if (dirtyFlag_[12]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    } else {
      sql += "default,";
    }
    if (parametersCount > 0) {
      sql.resize(sql.length() - 1);
    }
    if (needSelection) {
      sql.append(") returning *");
    } else {
      sql.append(1, ')');
    }
    LOG_TRACE << sql;
    return sql;
  }
};
} // namespace los_css_drogon
} // namespace drogon_model
