/**
 *
 *  PlantingAreas.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PlantingAreas.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::los_css_drogon;

const std::string PlantingAreas::Cols::_id = "\"id\"";
const std::string PlantingAreas::Cols::_area_name = "\"area_name\"";
const std::string PlantingAreas::Cols::_soil_type = "\"soil_type\"";
const std::string PlantingAreas::Cols::_size = "\"size\"";
const std::string PlantingAreas::Cols::_location = "\"location\"";
const std::string PlantingAreas::Cols::_status = "\"status\"";
const std::string PlantingAreas::Cols::_description = "\"description\"";
const std::string PlantingAreas::Cols::_created_at = "\"created_at\"";
const std::string PlantingAreas::Cols::_updated_at = "\"updated_at\"";
const std::string PlantingAreas::primaryKeyName = "id";
const bool PlantingAreas::hasPrimaryKey = true;
const std::string PlantingAreas::tableName = "\"planting_areas\"";

const std::vector<typename PlantingAreas::MetaData> PlantingAreas::metaData_ = {
    {"id", "int32_t", "integer", 4, 1, 1, 1},
    {"area_name", "std::string", "character varying", 128, 0, 0, 1},
    {"soil_type", "std::string", "character varying", 16, 0, 0, 1},
    {"size", "std::string", "numeric", 0, 0, 0, 1},
    {"location", "std::string", "character varying", 256, 0, 0, 1},
    {"status", "std::string", "character varying", 16, 0, 0, 1},
    {"description", "std::string", "text", 0, 0, 0, 0},
    {"created_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1},
    {"updated_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1}};
const std::string &PlantingAreas::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
PlantingAreas::PlantingAreas(const Row &r, const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["id"].isNull()) {
      id_ = std::make_shared<int32_t>(r["id"].as<int32_t>());
    }
    if (!r["area_name"].isNull()) {
      areaName_ = std::make_shared<std::string>(r["area_name"].as<std::string>());
    }
    if (!r["soil_type"].isNull()) {
      soilType_ = std::make_shared<std::string>(r["soil_type"].as<std::string>());
    }
    if (!r["size"].isNull()) {
      size_ = std::make_shared<std::string>(r["size"].as<std::string>());
    }
    if (!r["location"].isNull()) {
      location_ = std::make_shared<std::string>(r["location"].as<std::string>());
    }
    if (!r["status"].isNull()) {
      status_ = std::make_shared<std::string>(r["status"].as<std::string>());
    }
    if (!r["description"].isNull()) {
      description_ = std::make_shared<std::string>(r["description"].as<std::string>());
    }
    if (!r["created_at"].isNull()) {
      auto timeStr = r["created_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    if (!r["updated_at"].isNull()) {
      auto timeStr = r["updated_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 9 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      id_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      areaName_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 2;
    if (!r[index].isNull()) {
      soilType_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 3;
    if (!r[index].isNull()) {
      size_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 4;
    if (!r[index].isNull()) {
      location_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 5;
    if (!r[index].isNull()) {
      status_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 6;
    if (!r[index].isNull()) {
      description_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 7;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    index = offset + 8;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

PlantingAreas::PlantingAreas(const Json::Value &pJson,
                             const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 9) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      areaName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      soilType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      size_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      location_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      status_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      description_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[7]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[8]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

PlantingAreas::PlantingAreas(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    dirtyFlag_[0] = true;
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("area_name")) {
    dirtyFlag_[1] = true;
    if (!pJson["area_name"].isNull()) {
      areaName_ = std::make_shared<std::string>(pJson["area_name"].asString());
    }
  }
  if (pJson.isMember("soil_type")) {
    dirtyFlag_[2] = true;
    if (!pJson["soil_type"].isNull()) {
      soilType_ = std::make_shared<std::string>(pJson["soil_type"].asString());
    }
  }
  if (pJson.isMember("size")) {
    dirtyFlag_[3] = true;
    if (!pJson["size"].isNull()) {
      size_ = std::make_shared<std::string>(pJson["size"].asString());
    }
  }
  if (pJson.isMember("location")) {
    dirtyFlag_[4] = true;
    if (!pJson["location"].isNull()) {
      location_ = std::make_shared<std::string>(pJson["location"].asString());
    }
  }
  if (pJson.isMember("status")) {
    dirtyFlag_[5] = true;
    if (!pJson["status"].isNull()) {
      status_ = std::make_shared<std::string>(pJson["status"].asString());
    }
  }
  if (pJson.isMember("description")) {
    dirtyFlag_[6] = true;
    if (!pJson["description"].isNull()) {
      description_ = std::make_shared<std::string>(pJson["description"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[7] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[8] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void PlantingAreas::updateByMasqueradedJson(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 9) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      areaName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      soilType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      size_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      location_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      status_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      description_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[7]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[8]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void PlantingAreas::updateByJson(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("area_name")) {
    dirtyFlag_[1] = true;
    if (!pJson["area_name"].isNull()) {
      areaName_ = std::make_shared<std::string>(pJson["area_name"].asString());
    }
  }
  if (pJson.isMember("soil_type")) {
    dirtyFlag_[2] = true;
    if (!pJson["soil_type"].isNull()) {
      soilType_ = std::make_shared<std::string>(pJson["soil_type"].asString());
    }
  }
  if (pJson.isMember("size")) {
    dirtyFlag_[3] = true;
    if (!pJson["size"].isNull()) {
      size_ = std::make_shared<std::string>(pJson["size"].asString());
    }
  }
  if (pJson.isMember("location")) {
    dirtyFlag_[4] = true;
    if (!pJson["location"].isNull()) {
      location_ = std::make_shared<std::string>(pJson["location"].asString());
    }
  }
  if (pJson.isMember("status")) {
    dirtyFlag_[5] = true;
    if (!pJson["status"].isNull()) {
      status_ = std::make_shared<std::string>(pJson["status"].asString());
    }
  }
  if (pJson.isMember("description")) {
    dirtyFlag_[6] = true;
    if (!pJson["description"].isNull()) {
      description_ = std::make_shared<std::string>(pJson["description"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[7] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[8] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

const int32_t &PlantingAreas::getValueOfId() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (id_)
    return *id_;
  return defaultValue;
}
const std::shared_ptr<int32_t> &PlantingAreas::getId() const noexcept { return id_; }
void PlantingAreas::setId(const int32_t &pId) noexcept {
  id_ = std::make_shared<int32_t>(pId);
  dirtyFlag_[0] = true;
}
const typename PlantingAreas::PrimaryKeyType &PlantingAreas::getPrimaryKey() const {
  assert(id_);
  return *id_;
}

const std::string &PlantingAreas::getValueOfAreaName() const noexcept {
  static const std::string defaultValue = std::string();
  if (areaName_)
    return *areaName_;
  return defaultValue;
}
const std::shared_ptr<std::string> &PlantingAreas::getAreaName() const noexcept {
  return areaName_;
}
void PlantingAreas::setAreaName(const std::string &pAreaName) noexcept {
  areaName_ = std::make_shared<std::string>(pAreaName);
  dirtyFlag_[1] = true;
}
void PlantingAreas::setAreaName(std::string &&pAreaName) noexcept {
  areaName_ = std::make_shared<std::string>(std::move(pAreaName));
  dirtyFlag_[1] = true;
}

const std::string &PlantingAreas::getValueOfSoilType() const noexcept {
  static const std::string defaultValue = std::string();
  if (soilType_)
    return *soilType_;
  return defaultValue;
}
const std::shared_ptr<std::string> &PlantingAreas::getSoilType() const noexcept {
  return soilType_;
}
void PlantingAreas::setSoilType(const std::string &pSoilType) noexcept {
  soilType_ = std::make_shared<std::string>(pSoilType);
  dirtyFlag_[2] = true;
}
void PlantingAreas::setSoilType(std::string &&pSoilType) noexcept {
  soilType_ = std::make_shared<std::string>(std::move(pSoilType));
  dirtyFlag_[2] = true;
}

const std::string &PlantingAreas::getValueOfSize() const noexcept {
  static const std::string defaultValue = std::string();
  if (size_)
    return *size_;
  return defaultValue;
}
const std::shared_ptr<std::string> &PlantingAreas::getSize() const noexcept { return size_; }
void PlantingAreas::setSize(const std::string &pSize) noexcept {
  size_ = std::make_shared<std::string>(pSize);
  dirtyFlag_[3] = true;
}
void PlantingAreas::setSize(std::string &&pSize) noexcept {
  size_ = std::make_shared<std::string>(std::move(pSize));
  dirtyFlag_[3] = true;
}

const std::string &PlantingAreas::getValueOfLocation() const noexcept {
  static const std::string defaultValue = std::string();
  if (location_)
    return *location_;
  return defaultValue;
}
const std::shared_ptr<std::string> &PlantingAreas::getLocation() const noexcept {
  return location_;
}
void PlantingAreas::setLocation(const std::string &pLocation) noexcept {
  location_ = std::make_shared<std::string>(pLocation);
  dirtyFlag_[4] = true;
}
void PlantingAreas::setLocation(std::string &&pLocation) noexcept {
  location_ = std::make_shared<std::string>(std::move(pLocation));
  dirtyFlag_[4] = true;
}

const std::string &PlantingAreas::getValueOfStatus() const noexcept {
  static const std::string defaultValue = std::string();
  if (status_)
    return *status_;
  return defaultValue;
}
const std::shared_ptr<std::string> &PlantingAreas::getStatus() const noexcept { return status_; }
void PlantingAreas::setStatus(const std::string &pStatus) noexcept {
  status_ = std::make_shared<std::string>(pStatus);
  dirtyFlag_[5] = true;
}
void PlantingAreas::setStatus(std::string &&pStatus) noexcept {
  status_ = std::make_shared<std::string>(std::move(pStatus));
  dirtyFlag_[5] = true;
}

const std::string &PlantingAreas::getValueOfDescription() const noexcept {
  static const std::string defaultValue = std::string();
  if (description_)
    return *description_;
  return defaultValue;
}
const std::shared_ptr<std::string> &PlantingAreas::getDescription() const noexcept {
  return description_;
}
void PlantingAreas::setDescription(const std::string &pDescription) noexcept {
  description_ = std::make_shared<std::string>(pDescription);
  dirtyFlag_[6] = true;
}
void PlantingAreas::setDescription(std::string &&pDescription) noexcept {
  description_ = std::make_shared<std::string>(std::move(pDescription));
  dirtyFlag_[6] = true;
}
void PlantingAreas::setDescriptionToNull() noexcept {
  description_.reset();
  dirtyFlag_[6] = true;
}

const ::trantor::Date &PlantingAreas::getValueOfCreatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (createdAt_)
    return *createdAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PlantingAreas::getCreatedAt() const noexcept {
  return createdAt_;
}
void PlantingAreas::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept {
  createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
  dirtyFlag_[7] = true;
}

const ::trantor::Date &PlantingAreas::getValueOfUpdatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (updatedAt_)
    return *updatedAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PlantingAreas::getUpdatedAt() const noexcept {
  return updatedAt_;
}
void PlantingAreas::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept {
  updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
  dirtyFlag_[8] = true;
}

void PlantingAreas::updateId(const uint64_t id) {}

const std::vector<std::string> &PlantingAreas::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {"area_name",  "soil_type", "size",
                                                  "location",   "status",    "description",
                                                  "created_at", "updated_at"};
  return inCols;
}

void PlantingAreas::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getAreaName()) {
      binder << getValueOfAreaName();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getSoilType()) {
      binder << getValueOfSoilType();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getSize()) {
      binder << getValueOfSize();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getLocation()) {
      binder << getValueOfLocation();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getStatus()) {
      binder << getValueOfStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getDescription()) {
      binder << getValueOfDescription();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> PlantingAreas::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  if (dirtyFlag_[2]) {
    ret.push_back(getColumnName(2));
  }
  if (dirtyFlag_[3]) {
    ret.push_back(getColumnName(3));
  }
  if (dirtyFlag_[4]) {
    ret.push_back(getColumnName(4));
  }
  if (dirtyFlag_[5]) {
    ret.push_back(getColumnName(5));
  }
  if (dirtyFlag_[6]) {
    ret.push_back(getColumnName(6));
  }
  if (dirtyFlag_[7]) {
    ret.push_back(getColumnName(7));
  }
  if (dirtyFlag_[8]) {
    ret.push_back(getColumnName(8));
  }
  return ret;
}

void PlantingAreas::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getAreaName()) {
      binder << getValueOfAreaName();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getSoilType()) {
      binder << getValueOfSoilType();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getSize()) {
      binder << getValueOfSize();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getLocation()) {
      binder << getValueOfLocation();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getStatus()) {
      binder << getValueOfStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getDescription()) {
      binder << getValueOfDescription();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value PlantingAreas::toJson() const {
  Json::Value ret;
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getAreaName()) {
    ret["area_name"] = getValueOfAreaName();
  } else {
    ret["area_name"] = Json::Value();
  }
  if (getSoilType()) {
    ret["soil_type"] = getValueOfSoilType();
  } else {
    ret["soil_type"] = Json::Value();
  }
  if (getSize()) {
    ret["size"] = getValueOfSize();
  } else {
    ret["size"] = Json::Value();
  }
  if (getLocation()) {
    ret["location"] = getValueOfLocation();
  } else {
    ret["location"] = Json::Value();
  }
  if (getStatus()) {
    ret["status"] = getValueOfStatus();
  } else {
    ret["status"] = Json::Value();
  }
  if (getDescription()) {
    ret["description"] = getValueOfDescription();
  } else {
    ret["description"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

Json::Value
PlantingAreas::toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 9) {
    if (!pMasqueradingVector[0].empty()) {
      if (getId()) {
        ret[pMasqueradingVector[0]] = getValueOfId();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getAreaName()) {
        ret[pMasqueradingVector[1]] = getValueOfAreaName();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (getSoilType()) {
        ret[pMasqueradingVector[2]] = getValueOfSoilType();
      } else {
        ret[pMasqueradingVector[2]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (getSize()) {
        ret[pMasqueradingVector[3]] = getValueOfSize();
      } else {
        ret[pMasqueradingVector[3]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (getLocation()) {
        ret[pMasqueradingVector[4]] = getValueOfLocation();
      } else {
        ret[pMasqueradingVector[4]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (getStatus()) {
        ret[pMasqueradingVector[5]] = getValueOfStatus();
      } else {
        ret[pMasqueradingVector[5]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (getDescription()) {
        ret[pMasqueradingVector[6]] = getValueOfDescription();
      } else {
        ret[pMasqueradingVector[6]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (getCreatedAt()) {
        ret[pMasqueradingVector[7]] = getCreatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[7]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (getUpdatedAt()) {
        ret[pMasqueradingVector[8]] = getUpdatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[8]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getAreaName()) {
    ret["area_name"] = getValueOfAreaName();
  } else {
    ret["area_name"] = Json::Value();
  }
  if (getSoilType()) {
    ret["soil_type"] = getValueOfSoilType();
  } else {
    ret["soil_type"] = Json::Value();
  }
  if (getSize()) {
    ret["size"] = getValueOfSize();
  } else {
    ret["size"] = Json::Value();
  }
  if (getLocation()) {
    ret["location"] = getValueOfLocation();
  } else {
    ret["location"] = Json::Value();
  }
  if (getStatus()) {
    ret["status"] = getValueOfStatus();
  } else {
    ret["status"] = Json::Value();
  }
  if (getDescription()) {
    ret["description"] = getValueOfDescription();
  } else {
    ret["description"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

bool PlantingAreas::validateJsonForCreation(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, true))
      return false;
  }
  if (pJson.isMember("area_name")) {
    if (!validJsonOfField(1, "area_name", pJson["area_name"], err, true))
      return false;
  } else {
    err = "The area_name column cannot be null";
    return false;
  }
  if (pJson.isMember("soil_type")) {
    if (!validJsonOfField(2, "soil_type", pJson["soil_type"], err, true))
      return false;
  } else {
    err = "The soil_type column cannot be null";
    return false;
  }
  if (pJson.isMember("size")) {
    if (!validJsonOfField(3, "size", pJson["size"], err, true))
      return false;
  } else {
    err = "The size column cannot be null";
    return false;
  }
  if (pJson.isMember("location")) {
    if (!validJsonOfField(4, "location", pJson["location"], err, true))
      return false;
  } else {
    err = "The location column cannot be null";
    return false;
  }
  if (pJson.isMember("status")) {
    if (!validJsonOfField(5, "status", pJson["status"], err, true))
      return false;
  } else {
    err = "The status column cannot be null";
    return false;
  }
  if (pJson.isMember("description")) {
    if (!validJsonOfField(6, "description", pJson["description"], err, true))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(7, "created_at", pJson["created_at"], err, true))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(8, "updated_at", pJson["updated_at"], err, true))
      return false;
  }
  return true;
}
bool PlantingAreas::validateMasqueradedJsonForCreation(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 9) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[1] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (pJson.isMember(pMasqueradingVector[2])) {
        if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[2] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (pJson.isMember(pMasqueradingVector[3])) {
        if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[3] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (pJson.isMember(pMasqueradingVector[4])) {
        if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[4] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (pJson.isMember(pMasqueradingVector[5])) {
        if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[5] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (pJson.isMember(pMasqueradingVector[6])) {
        if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (pJson.isMember(pMasqueradingVector[7])) {
        if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (pJson.isMember(pMasqueradingVector[8])) {
        if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
          return false;
      }
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool PlantingAreas::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, false))
      return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("area_name")) {
    if (!validJsonOfField(1, "area_name", pJson["area_name"], err, false))
      return false;
  }
  if (pJson.isMember("soil_type")) {
    if (!validJsonOfField(2, "soil_type", pJson["soil_type"], err, false))
      return false;
  }
  if (pJson.isMember("size")) {
    if (!validJsonOfField(3, "size", pJson["size"], err, false))
      return false;
  }
  if (pJson.isMember("location")) {
    if (!validJsonOfField(4, "location", pJson["location"], err, false))
      return false;
  }
  if (pJson.isMember("status")) {
    if (!validJsonOfField(5, "status", pJson["status"], err, false))
      return false;
  }
  if (pJson.isMember("description")) {
    if (!validJsonOfField(6, "description", pJson["description"], err, false))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(7, "created_at", pJson["created_at"], err, false))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(8, "updated_at", pJson["updated_at"], err, false))
      return false;
  }
  return true;
}
bool PlantingAreas::validateMasqueradedJsonForUpdate(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 9) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err = "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
        return false;
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
      if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
        return false;
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
      if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
        return false;
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
      if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
        return false;
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
      if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
        return false;
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
      if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
        return false;
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
      if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
        return false;
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
      if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
        return false;
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool PlantingAreas::validJsonOfField(size_t index, const std::string &fieldName,
                                     const Json::Value &pJson, std::string &err,
                                     bool isForCreation) {
  switch (index) {
  case 0:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (isForCreation) {
      err = "The automatic primary key cannot be set";
      return false;
    }
    if (!pJson.isInt()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 1:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 128) {
      err =
          "String length exceeds limit for the " + fieldName + " field (the maximum value is 128)";
      return false;
    }

    break;
  case 2:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 3:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 4:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 256) {
      err =
          "String length exceeds limit for the " + fieldName + " field (the maximum value is 256)";
      return false;
    }

    break;
  case 5:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 6:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 7:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 8:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  default:
    err = "Internal error in the server";
    return false;
  }
  return true;
}
