/**
 *
 *  ProcessingFlows.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ProcessingFlows.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::los_css_drogon;

const std::string ProcessingFlows::Cols::_id = "\"id\"";
const std::string ProcessingFlows::Cols::_flow_name = "\"flow_name\"";
const std::string ProcessingFlows::Cols::_flow_type = "\"flow_type\"";
const std::string ProcessingFlows::Cols::_device_id = "\"device_id\"";
const std::string ProcessingFlows::Cols::_operator = "\"operator\"";
const std::string ProcessingFlows::Cols::_start_time = "\"start_time\"";
const std::string ProcessingFlows::Cols::_end_time = "\"end_time\"";
const std::string ProcessingFlows::Cols::_percent_complete = "\"percent_complete\"";
const std::string ProcessingFlows::Cols::_standard_hours = "\"standard_hours\"";
const std::string ProcessingFlows::Cols::_actual_hours = "\"actual_hours\"";
const std::string ProcessingFlows::Cols::_status = "\"status\"";
const std::string ProcessingFlows::Cols::_created_at = "\"created_at\"";
const std::string ProcessingFlows::Cols::_updated_at = "\"updated_at\"";
const std::string ProcessingFlows::primaryKeyName = "id";
const bool ProcessingFlows::hasPrimaryKey = true;
const std::string ProcessingFlows::tableName = "\"processing_flows\"";

const std::vector<typename ProcessingFlows::MetaData> ProcessingFlows::metaData_ = {
    {"id", "int32_t", "integer", 4, 1, 1, 1},
    {"flow_name", "std::string", "character varying", 128, 0, 0, 1},
    {"flow_type", "std::string", "character varying", 16, 0, 0, 1},
    {"device_id", "int32_t", "integer", 4, 0, 0, 1},
    {"operator", "std::string", "character varying", 64, 0, 0, 1},
    {"start_time", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 0},
    {"end_time", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 0},
    {"percent_complete", "std::string", "numeric", 0, 0, 0, 1},
    {"standard_hours", "std::string", "numeric", 0, 0, 0, 1},
    {"actual_hours", "std::string", "numeric", 0, 0, 0, 0},
    {"status", "std::string", "character varying", 16, 0, 0, 1},
    {"created_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1},
    {"updated_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1}};
const std::string &ProcessingFlows::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
ProcessingFlows::ProcessingFlows(const Row &r, const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["id"].isNull()) {
      id_ = std::make_shared<int32_t>(r["id"].as<int32_t>());
    }
    if (!r["flow_name"].isNull()) {
      flowName_ = std::make_shared<std::string>(r["flow_name"].as<std::string>());
    }
    if (!r["flow_type"].isNull()) {
      flowType_ = std::make_shared<std::string>(r["flow_type"].as<std::string>());
    }
    if (!r["device_id"].isNull()) {
      deviceId_ = std::make_shared<int32_t>(r["device_id"].as<int32_t>());
    }
    if (!r["operator"].isNull()) {
      operator_ = std::make_shared<std::string>(r["operator"].as<std::string>());
    }
    if (!r["start_time"].isNull()) {
      auto timeStr = r["start_time"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    if (!r["end_time"].isNull()) {
      auto timeStr = r["end_time"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    if (!r["percent_complete"].isNull()) {
      percentComplete_ = std::make_shared<std::string>(r["percent_complete"].as<std::string>());
    }
    if (!r["standard_hours"].isNull()) {
      standardHours_ = std::make_shared<std::string>(r["standard_hours"].as<std::string>());
    }
    if (!r["actual_hours"].isNull()) {
      actualHours_ = std::make_shared<std::string>(r["actual_hours"].as<std::string>());
    }
    if (!r["status"].isNull()) {
      status_ = std::make_shared<std::string>(r["status"].as<std::string>());
    }
    if (!r["created_at"].isNull()) {
      auto timeStr = r["created_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    if (!r["updated_at"].isNull()) {
      auto timeStr = r["updated_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 13 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      id_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      flowName_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 2;
    if (!r[index].isNull()) {
      flowType_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 3;
    if (!r[index].isNull()) {
      deviceId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 4;
    if (!r[index].isNull()) {
      operator_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 5;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    index = offset + 6;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    index = offset + 7;
    if (!r[index].isNull()) {
      percentComplete_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 8;
    if (!r[index].isNull()) {
      standardHours_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 9;
    if (!r[index].isNull()) {
      actualHours_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 10;
    if (!r[index].isNull()) {
      status_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 11;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    index = offset + 12;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

ProcessingFlows::ProcessingFlows(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 13) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      flowName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      flowType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      deviceId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      operator_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[5]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[6]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      percentComplete_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      standardHours_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
    }
  }
  if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
    dirtyFlag_[9] = true;
    if (!pJson[pMasqueradingVector[9]].isNull()) {
      actualHours_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
    }
  }
  if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
    dirtyFlag_[10] = true;
    if (!pJson[pMasqueradingVector[10]].isNull()) {
      status_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
    }
  }
  if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
    dirtyFlag_[11] = true;
    if (!pJson[pMasqueradingVector[11]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[11]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
    dirtyFlag_[12] = true;
    if (!pJson[pMasqueradingVector[12]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[12]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

ProcessingFlows::ProcessingFlows(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    dirtyFlag_[0] = true;
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("flow_name")) {
    dirtyFlag_[1] = true;
    if (!pJson["flow_name"].isNull()) {
      flowName_ = std::make_shared<std::string>(pJson["flow_name"].asString());
    }
  }
  if (pJson.isMember("flow_type")) {
    dirtyFlag_[2] = true;
    if (!pJson["flow_type"].isNull()) {
      flowType_ = std::make_shared<std::string>(pJson["flow_type"].asString());
    }
  }
  if (pJson.isMember("device_id")) {
    dirtyFlag_[3] = true;
    if (!pJson["device_id"].isNull()) {
      deviceId_ = std::make_shared<int32_t>((int32_t)pJson["device_id"].asInt64());
    }
  }
  if (pJson.isMember("operator")) {
    dirtyFlag_[4] = true;
    if (!pJson["operator"].isNull()) {
      operator_ = std::make_shared<std::string>(pJson["operator"].asString());
    }
  }
  if (pJson.isMember("start_time")) {
    dirtyFlag_[5] = true;
    if (!pJson["start_time"].isNull()) {
      auto timeStr = pJson["start_time"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("end_time")) {
    dirtyFlag_[6] = true;
    if (!pJson["end_time"].isNull()) {
      auto timeStr = pJson["end_time"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("percent_complete")) {
    dirtyFlag_[7] = true;
    if (!pJson["percent_complete"].isNull()) {
      percentComplete_ = std::make_shared<std::string>(pJson["percent_complete"].asString());
    }
  }
  if (pJson.isMember("standard_hours")) {
    dirtyFlag_[8] = true;
    if (!pJson["standard_hours"].isNull()) {
      standardHours_ = std::make_shared<std::string>(pJson["standard_hours"].asString());
    }
  }
  if (pJson.isMember("actual_hours")) {
    dirtyFlag_[9] = true;
    if (!pJson["actual_hours"].isNull()) {
      actualHours_ = std::make_shared<std::string>(pJson["actual_hours"].asString());
    }
  }
  if (pJson.isMember("status")) {
    dirtyFlag_[10] = true;
    if (!pJson["status"].isNull()) {
      status_ = std::make_shared<std::string>(pJson["status"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[11] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[12] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void ProcessingFlows::updateByMasqueradedJson(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 13) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      flowName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      flowType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      deviceId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      operator_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[5]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[6]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      percentComplete_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      standardHours_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
    }
  }
  if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
    dirtyFlag_[9] = true;
    if (!pJson[pMasqueradingVector[9]].isNull()) {
      actualHours_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
    }
  }
  if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
    dirtyFlag_[10] = true;
    if (!pJson[pMasqueradingVector[10]].isNull()) {
      status_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
    }
  }
  if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
    dirtyFlag_[11] = true;
    if (!pJson[pMasqueradingVector[11]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[11]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
    dirtyFlag_[12] = true;
    if (!pJson[pMasqueradingVector[12]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[12]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void ProcessingFlows::updateByJson(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("flow_name")) {
    dirtyFlag_[1] = true;
    if (!pJson["flow_name"].isNull()) {
      flowName_ = std::make_shared<std::string>(pJson["flow_name"].asString());
    }
  }
  if (pJson.isMember("flow_type")) {
    dirtyFlag_[2] = true;
    if (!pJson["flow_type"].isNull()) {
      flowType_ = std::make_shared<std::string>(pJson["flow_type"].asString());
    }
  }
  if (pJson.isMember("device_id")) {
    dirtyFlag_[3] = true;
    if (!pJson["device_id"].isNull()) {
      deviceId_ = std::make_shared<int32_t>((int32_t)pJson["device_id"].asInt64());
    }
  }
  if (pJson.isMember("operator")) {
    dirtyFlag_[4] = true;
    if (!pJson["operator"].isNull()) {
      operator_ = std::make_shared<std::string>(pJson["operator"].asString());
    }
  }
  if (pJson.isMember("start_time")) {
    dirtyFlag_[5] = true;
    if (!pJson["start_time"].isNull()) {
      auto timeStr = pJson["start_time"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("end_time")) {
    dirtyFlag_[6] = true;
    if (!pJson["end_time"].isNull()) {
      auto timeStr = pJson["end_time"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("percent_complete")) {
    dirtyFlag_[7] = true;
    if (!pJson["percent_complete"].isNull()) {
      percentComplete_ = std::make_shared<std::string>(pJson["percent_complete"].asString());
    }
  }
  if (pJson.isMember("standard_hours")) {
    dirtyFlag_[8] = true;
    if (!pJson["standard_hours"].isNull()) {
      standardHours_ = std::make_shared<std::string>(pJson["standard_hours"].asString());
    }
  }
  if (pJson.isMember("actual_hours")) {
    dirtyFlag_[9] = true;
    if (!pJson["actual_hours"].isNull()) {
      actualHours_ = std::make_shared<std::string>(pJson["actual_hours"].asString());
    }
  }
  if (pJson.isMember("status")) {
    dirtyFlag_[10] = true;
    if (!pJson["status"].isNull()) {
      status_ = std::make_shared<std::string>(pJson["status"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[11] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[12] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

const int32_t &ProcessingFlows::getValueOfId() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (id_)
    return *id_;
  return defaultValue;
}
const std::shared_ptr<int32_t> &ProcessingFlows::getId() const noexcept { return id_; }
void ProcessingFlows::setId(const int32_t &pId) noexcept {
  id_ = std::make_shared<int32_t>(pId);
  dirtyFlag_[0] = true;
}
const typename ProcessingFlows::PrimaryKeyType &ProcessingFlows::getPrimaryKey() const {
  assert(id_);
  return *id_;
}

const std::string &ProcessingFlows::getValueOfFlowName() const noexcept {
  static const std::string defaultValue = std::string();
  if (flowName_)
    return *flowName_;
  return defaultValue;
}
const std::shared_ptr<std::string> &ProcessingFlows::getFlowName() const noexcept {
  return flowName_;
}
void ProcessingFlows::setFlowName(const std::string &pFlowName) noexcept {
  flowName_ = std::make_shared<std::string>(pFlowName);
  dirtyFlag_[1] = true;
}
void ProcessingFlows::setFlowName(std::string &&pFlowName) noexcept {
  flowName_ = std::make_shared<std::string>(std::move(pFlowName));
  dirtyFlag_[1] = true;
}

const std::string &ProcessingFlows::getValueOfFlowType() const noexcept {
  static const std::string defaultValue = std::string();
  if (flowType_)
    return *flowType_;
  return defaultValue;
}
const std::shared_ptr<std::string> &ProcessingFlows::getFlowType() const noexcept {
  return flowType_;
}
void ProcessingFlows::setFlowType(const std::string &pFlowType) noexcept {
  flowType_ = std::make_shared<std::string>(pFlowType);
  dirtyFlag_[2] = true;
}
void ProcessingFlows::setFlowType(std::string &&pFlowType) noexcept {
  flowType_ = std::make_shared<std::string>(std::move(pFlowType));
  dirtyFlag_[2] = true;
}

const int32_t &ProcessingFlows::getValueOfDeviceId() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (deviceId_)
    return *deviceId_;
  return defaultValue;
}
const std::shared_ptr<int32_t> &ProcessingFlows::getDeviceId() const noexcept { return deviceId_; }
void ProcessingFlows::setDeviceId(const int32_t &pDeviceId) noexcept {
  deviceId_ = std::make_shared<int32_t>(pDeviceId);
  dirtyFlag_[3] = true;
}

const std::string &ProcessingFlows::getValueOfOperator() const noexcept {
  static const std::string defaultValue = std::string();
  if (operator_)
    return *operator_;
  return defaultValue;
}
const std::shared_ptr<std::string> &ProcessingFlows::getOperator() const noexcept {
  return operator_;
}
void ProcessingFlows::setOperator(const std::string &pOperator) noexcept {
  operator_ = std::make_shared<std::string>(pOperator);
  dirtyFlag_[4] = true;
}
void ProcessingFlows::setOperator(std::string &&pOperator) noexcept {
  operator_ = std::make_shared<std::string>(std::move(pOperator));
  dirtyFlag_[4] = true;
}

const ::trantor::Date &ProcessingFlows::getValueOfStartTime() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (startTime_)
    return *startTime_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProcessingFlows::getStartTime() const noexcept {
  return startTime_;
}
void ProcessingFlows::setStartTime(const ::trantor::Date &pStartTime) noexcept {
  startTime_ = std::make_shared<::trantor::Date>(pStartTime);
  dirtyFlag_[5] = true;
}
void ProcessingFlows::setStartTimeToNull() noexcept {
  startTime_.reset();
  dirtyFlag_[5] = true;
}

const ::trantor::Date &ProcessingFlows::getValueOfEndTime() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (endTime_)
    return *endTime_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProcessingFlows::getEndTime() const noexcept {
  return endTime_;
}
void ProcessingFlows::setEndTime(const ::trantor::Date &pEndTime) noexcept {
  endTime_ = std::make_shared<::trantor::Date>(pEndTime);
  dirtyFlag_[6] = true;
}
void ProcessingFlows::setEndTimeToNull() noexcept {
  endTime_.reset();
  dirtyFlag_[6] = true;
}

const std::string &ProcessingFlows::getValueOfPercentComplete() const noexcept {
  static const std::string defaultValue = std::string();
  if (percentComplete_)
    return *percentComplete_;
  return defaultValue;
}
const std::shared_ptr<std::string> &ProcessingFlows::getPercentComplete() const noexcept {
  return percentComplete_;
}
void ProcessingFlows::setPercentComplete(const std::string &pPercentComplete) noexcept {
  percentComplete_ = std::make_shared<std::string>(pPercentComplete);
  dirtyFlag_[7] = true;
}
void ProcessingFlows::setPercentComplete(std::string &&pPercentComplete) noexcept {
  percentComplete_ = std::make_shared<std::string>(std::move(pPercentComplete));
  dirtyFlag_[7] = true;
}

const std::string &ProcessingFlows::getValueOfStandardHours() const noexcept {
  static const std::string defaultValue = std::string();
  if (standardHours_)
    return *standardHours_;
  return defaultValue;
}
const std::shared_ptr<std::string> &ProcessingFlows::getStandardHours() const noexcept {
  return standardHours_;
}
void ProcessingFlows::setStandardHours(const std::string &pStandardHours) noexcept {
  standardHours_ = std::make_shared<std::string>(pStandardHours);
  dirtyFlag_[8] = true;
}
void ProcessingFlows::setStandardHours(std::string &&pStandardHours) noexcept {
  standardHours_ = std::make_shared<std::string>(std::move(pStandardHours));
  dirtyFlag_[8] = true;
}

const std::string &ProcessingFlows::getValueOfActualHours() const noexcept {
  static const std::string defaultValue = std::string();
  if (actualHours_)
    return *actualHours_;
  return defaultValue;
}
const std::shared_ptr<std::string> &ProcessingFlows::getActualHours() const noexcept {
  return actualHours_;
}
void ProcessingFlows::setActualHours(const std::string &pActualHours) noexcept {
  actualHours_ = std::make_shared<std::string>(pActualHours);
  dirtyFlag_[9] = true;
}
void ProcessingFlows::setActualHours(std::string &&pActualHours) noexcept {
  actualHours_ = std::make_shared<std::string>(std::move(pActualHours));
  dirtyFlag_[9] = true;
}
void ProcessingFlows::setActualHoursToNull() noexcept {
  actualHours_.reset();
  dirtyFlag_[9] = true;
}

const std::string &ProcessingFlows::getValueOfStatus() const noexcept {
  static const std::string defaultValue = std::string();
  if (status_)
    return *status_;
  return defaultValue;
}
const std::shared_ptr<std::string> &ProcessingFlows::getStatus() const noexcept { return status_; }
void ProcessingFlows::setStatus(const std::string &pStatus) noexcept {
  status_ = std::make_shared<std::string>(pStatus);
  dirtyFlag_[10] = true;
}
void ProcessingFlows::setStatus(std::string &&pStatus) noexcept {
  status_ = std::make_shared<std::string>(std::move(pStatus));
  dirtyFlag_[10] = true;
}

const ::trantor::Date &ProcessingFlows::getValueOfCreatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (createdAt_)
    return *createdAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProcessingFlows::getCreatedAt() const noexcept {
  return createdAt_;
}
void ProcessingFlows::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept {
  createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
  dirtyFlag_[11] = true;
}

const ::trantor::Date &ProcessingFlows::getValueOfUpdatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (updatedAt_)
    return *updatedAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProcessingFlows::getUpdatedAt() const noexcept {
  return updatedAt_;
}
void ProcessingFlows::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept {
  updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
  dirtyFlag_[12] = true;
}

void ProcessingFlows::updateId(const uint64_t id) {}

const std::vector<std::string> &ProcessingFlows::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {
      "flow_name",        "flow_type",      "device_id",    "operator", "start_time", "end_time",
      "percent_complete", "standard_hours", "actual_hours", "status",   "created_at", "updated_at"};
  return inCols;
}

void ProcessingFlows::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getFlowName()) {
      binder << getValueOfFlowName();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getFlowType()) {
      binder << getValueOfFlowType();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getDeviceId()) {
      binder << getValueOfDeviceId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getOperator()) {
      binder << getValueOfOperator();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getStartTime()) {
      binder << getValueOfStartTime();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getEndTime()) {
      binder << getValueOfEndTime();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getPercentComplete()) {
      binder << getValueOfPercentComplete();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getStandardHours()) {
      binder << getValueOfStandardHours();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[9]) {
    if (getActualHours()) {
      binder << getValueOfActualHours();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[10]) {
    if (getStatus()) {
      binder << getValueOfStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[11]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[12]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> ProcessingFlows::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  if (dirtyFlag_[2]) {
    ret.push_back(getColumnName(2));
  }
  if (dirtyFlag_[3]) {
    ret.push_back(getColumnName(3));
  }
  if (dirtyFlag_[4]) {
    ret.push_back(getColumnName(4));
  }
  if (dirtyFlag_[5]) {
    ret.push_back(getColumnName(5));
  }
  if (dirtyFlag_[6]) {
    ret.push_back(getColumnName(6));
  }
  if (dirtyFlag_[7]) {
    ret.push_back(getColumnName(7));
  }
  if (dirtyFlag_[8]) {
    ret.push_back(getColumnName(8));
  }
  if (dirtyFlag_[9]) {
    ret.push_back(getColumnName(9));
  }
  if (dirtyFlag_[10]) {
    ret.push_back(getColumnName(10));
  }
  if (dirtyFlag_[11]) {
    ret.push_back(getColumnName(11));
  }
  if (dirtyFlag_[12]) {
    ret.push_back(getColumnName(12));
  }
  return ret;
}

void ProcessingFlows::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getFlowName()) {
      binder << getValueOfFlowName();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getFlowType()) {
      binder << getValueOfFlowType();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getDeviceId()) {
      binder << getValueOfDeviceId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getOperator()) {
      binder << getValueOfOperator();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getStartTime()) {
      binder << getValueOfStartTime();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getEndTime()) {
      binder << getValueOfEndTime();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getPercentComplete()) {
      binder << getValueOfPercentComplete();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getStandardHours()) {
      binder << getValueOfStandardHours();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[9]) {
    if (getActualHours()) {
      binder << getValueOfActualHours();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[10]) {
    if (getStatus()) {
      binder << getValueOfStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[11]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[12]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value ProcessingFlows::toJson() const {
  Json::Value ret;
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getFlowName()) {
    ret["flow_name"] = getValueOfFlowName();
  } else {
    ret["flow_name"] = Json::Value();
  }
  if (getFlowType()) {
    ret["flow_type"] = getValueOfFlowType();
  } else {
    ret["flow_type"] = Json::Value();
  }
  if (getDeviceId()) {
    ret["device_id"] = getValueOfDeviceId();
  } else {
    ret["device_id"] = Json::Value();
  }
  if (getOperator()) {
    ret["operator"] = getValueOfOperator();
  } else {
    ret["operator"] = Json::Value();
  }
  if (getStartTime()) {
    ret["start_time"] = getStartTime()->toDbStringLocal();
  } else {
    ret["start_time"] = Json::Value();
  }
  if (getEndTime()) {
    ret["end_time"] = getEndTime()->toDbStringLocal();
  } else {
    ret["end_time"] = Json::Value();
  }
  if (getPercentComplete()) {
    ret["percent_complete"] = getValueOfPercentComplete();
  } else {
    ret["percent_complete"] = Json::Value();
  }
  if (getStandardHours()) {
    ret["standard_hours"] = getValueOfStandardHours();
  } else {
    ret["standard_hours"] = Json::Value();
  }
  if (getActualHours()) {
    ret["actual_hours"] = getValueOfActualHours();
  } else {
    ret["actual_hours"] = Json::Value();
  }
  if (getStatus()) {
    ret["status"] = getValueOfStatus();
  } else {
    ret["status"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

Json::Value
ProcessingFlows::toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 13) {
    if (!pMasqueradingVector[0].empty()) {
      if (getId()) {
        ret[pMasqueradingVector[0]] = getValueOfId();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getFlowName()) {
        ret[pMasqueradingVector[1]] = getValueOfFlowName();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (getFlowType()) {
        ret[pMasqueradingVector[2]] = getValueOfFlowType();
      } else {
        ret[pMasqueradingVector[2]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (getDeviceId()) {
        ret[pMasqueradingVector[3]] = getValueOfDeviceId();
      } else {
        ret[pMasqueradingVector[3]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (getOperator()) {
        ret[pMasqueradingVector[4]] = getValueOfOperator();
      } else {
        ret[pMasqueradingVector[4]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (getStartTime()) {
        ret[pMasqueradingVector[5]] = getStartTime()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[5]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (getEndTime()) {
        ret[pMasqueradingVector[6]] = getEndTime()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[6]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (getPercentComplete()) {
        ret[pMasqueradingVector[7]] = getValueOfPercentComplete();
      } else {
        ret[pMasqueradingVector[7]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (getStandardHours()) {
        ret[pMasqueradingVector[8]] = getValueOfStandardHours();
      } else {
        ret[pMasqueradingVector[8]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[9].empty()) {
      if (getActualHours()) {
        ret[pMasqueradingVector[9]] = getValueOfActualHours();
      } else {
        ret[pMasqueradingVector[9]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[10].empty()) {
      if (getStatus()) {
        ret[pMasqueradingVector[10]] = getValueOfStatus();
      } else {
        ret[pMasqueradingVector[10]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[11].empty()) {
      if (getCreatedAt()) {
        ret[pMasqueradingVector[11]] = getCreatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[11]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[12].empty()) {
      if (getUpdatedAt()) {
        ret[pMasqueradingVector[12]] = getUpdatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[12]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getFlowName()) {
    ret["flow_name"] = getValueOfFlowName();
  } else {
    ret["flow_name"] = Json::Value();
  }
  if (getFlowType()) {
    ret["flow_type"] = getValueOfFlowType();
  } else {
    ret["flow_type"] = Json::Value();
  }
  if (getDeviceId()) {
    ret["device_id"] = getValueOfDeviceId();
  } else {
    ret["device_id"] = Json::Value();
  }
  if (getOperator()) {
    ret["operator"] = getValueOfOperator();
  } else {
    ret["operator"] = Json::Value();
  }
  if (getStartTime()) {
    ret["start_time"] = getStartTime()->toDbStringLocal();
  } else {
    ret["start_time"] = Json::Value();
  }
  if (getEndTime()) {
    ret["end_time"] = getEndTime()->toDbStringLocal();
  } else {
    ret["end_time"] = Json::Value();
  }
  if (getPercentComplete()) {
    ret["percent_complete"] = getValueOfPercentComplete();
  } else {
    ret["percent_complete"] = Json::Value();
  }
  if (getStandardHours()) {
    ret["standard_hours"] = getValueOfStandardHours();
  } else {
    ret["standard_hours"] = Json::Value();
  }
  if (getActualHours()) {
    ret["actual_hours"] = getValueOfActualHours();
  } else {
    ret["actual_hours"] = Json::Value();
  }
  if (getStatus()) {
    ret["status"] = getValueOfStatus();
  } else {
    ret["status"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

bool ProcessingFlows::validateJsonForCreation(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, true))
      return false;
  }
  if (pJson.isMember("flow_name")) {
    if (!validJsonOfField(1, "flow_name", pJson["flow_name"], err, true))
      return false;
  } else {
    err = "The flow_name column cannot be null";
    return false;
  }
  if (pJson.isMember("flow_type")) {
    if (!validJsonOfField(2, "flow_type", pJson["flow_type"], err, true))
      return false;
  } else {
    err = "The flow_type column cannot be null";
    return false;
  }
  if (pJson.isMember("device_id")) {
    if (!validJsonOfField(3, "device_id", pJson["device_id"], err, true))
      return false;
  } else {
    err = "The device_id column cannot be null";
    return false;
  }
  if (pJson.isMember("operator")) {
    if (!validJsonOfField(4, "operator", pJson["operator"], err, true))
      return false;
  } else {
    err = "The operator column cannot be null";
    return false;
  }
  if (pJson.isMember("start_time")) {
    if (!validJsonOfField(5, "start_time", pJson["start_time"], err, true))
      return false;
  }
  if (pJson.isMember("end_time")) {
    if (!validJsonOfField(6, "end_time", pJson["end_time"], err, true))
      return false;
  }
  if (pJson.isMember("percent_complete")) {
    if (!validJsonOfField(7, "percent_complete", pJson["percent_complete"], err, true))
      return false;
  }
  if (pJson.isMember("standard_hours")) {
    if (!validJsonOfField(8, "standard_hours", pJson["standard_hours"], err, true))
      return false;
  } else {
    err = "The standard_hours column cannot be null";
    return false;
  }
  if (pJson.isMember("actual_hours")) {
    if (!validJsonOfField(9, "actual_hours", pJson["actual_hours"], err, true))
      return false;
  }
  if (pJson.isMember("status")) {
    if (!validJsonOfField(10, "status", pJson["status"], err, true))
      return false;
  } else {
    err = "The status column cannot be null";
    return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(11, "created_at", pJson["created_at"], err, true))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(12, "updated_at", pJson["updated_at"], err, true))
      return false;
  }
  return true;
}
bool ProcessingFlows::validateMasqueradedJsonForCreation(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 13) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[1] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (pJson.isMember(pMasqueradingVector[2])) {
        if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[2] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (pJson.isMember(pMasqueradingVector[3])) {
        if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[3] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (pJson.isMember(pMasqueradingVector[4])) {
        if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[4] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (pJson.isMember(pMasqueradingVector[5])) {
        if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (pJson.isMember(pMasqueradingVector[6])) {
        if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (pJson.isMember(pMasqueradingVector[7])) {
        if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (pJson.isMember(pMasqueradingVector[8])) {
        if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[8] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[9].empty()) {
      if (pJson.isMember(pMasqueradingVector[9])) {
        if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[10].empty()) {
      if (pJson.isMember(pMasqueradingVector[10])) {
        if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err,
                              true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[10] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[11].empty()) {
      if (pJson.isMember(pMasqueradingVector[11])) {
        if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err,
                              true))
          return false;
      }
    }
    if (!pMasqueradingVector[12].empty()) {
      if (pJson.isMember(pMasqueradingVector[12])) {
        if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err,
                              true))
          return false;
      }
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool ProcessingFlows::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, false))
      return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("flow_name")) {
    if (!validJsonOfField(1, "flow_name", pJson["flow_name"], err, false))
      return false;
  }
  if (pJson.isMember("flow_type")) {
    if (!validJsonOfField(2, "flow_type", pJson["flow_type"], err, false))
      return false;
  }
  if (pJson.isMember("device_id")) {
    if (!validJsonOfField(3, "device_id", pJson["device_id"], err, false))
      return false;
  }
  if (pJson.isMember("operator")) {
    if (!validJsonOfField(4, "operator", pJson["operator"], err, false))
      return false;
  }
  if (pJson.isMember("start_time")) {
    if (!validJsonOfField(5, "start_time", pJson["start_time"], err, false))
      return false;
  }
  if (pJson.isMember("end_time")) {
    if (!validJsonOfField(6, "end_time", pJson["end_time"], err, false))
      return false;
  }
  if (pJson.isMember("percent_complete")) {
    if (!validJsonOfField(7, "percent_complete", pJson["percent_complete"], err, false))
      return false;
  }
  if (pJson.isMember("standard_hours")) {
    if (!validJsonOfField(8, "standard_hours", pJson["standard_hours"], err, false))
      return false;
  }
  if (pJson.isMember("actual_hours")) {
    if (!validJsonOfField(9, "actual_hours", pJson["actual_hours"], err, false))
      return false;
  }
  if (pJson.isMember("status")) {
    if (!validJsonOfField(10, "status", pJson["status"], err, false))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(11, "created_at", pJson["created_at"], err, false))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(12, "updated_at", pJson["updated_at"], err, false))
      return false;
  }
  return true;
}
bool ProcessingFlows::validateMasqueradedJsonForUpdate(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 13) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err = "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
        return false;
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
      if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
        return false;
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
      if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
        return false;
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
      if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
        return false;
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
      if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
        return false;
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
      if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
        return false;
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
      if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
        return false;
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
      if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
        return false;
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
      if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
        return false;
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
      if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err,
                            false))
        return false;
    }
    if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
      if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err,
                            false))
        return false;
    }
    if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
      if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err,
                            false))
        return false;
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool ProcessingFlows::validJsonOfField(size_t index, const std::string &fieldName,
                                       const Json::Value &pJson, std::string &err,
                                       bool isForCreation) {
  switch (index) {
  case 0:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (isForCreation) {
      err = "The automatic primary key cannot be set";
      return false;
    }
    if (!pJson.isInt()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 1:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 128) {
      err =
          "String length exceeds limit for the " + fieldName + " field (the maximum value is 128)";
      return false;
    }

    break;
  case 2:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 3:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isInt()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 4:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 64) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 64)";
      return false;
    }

    break;
  case 5:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 6:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 7:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 8:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 9:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 10:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 11:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 12:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  default:
    err = "Internal error in the server";
    return false;
  }
  return true;
}
