/**
 *
 *  ProcessingFlows.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/BaseBuilder.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <iostream>
#include <json/json.h>
#include <memory>
#include <stdint.h>
#include <string>
#include <string_view>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <tuple>
#include <vector>

namespace drogon {
namespace orm {
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
} // namespace orm
} // namespace drogon
namespace drogon_model {
namespace los_css_drogon {

class ProcessingFlows {
public:
  struct Cols {
    static const std::string _id;
    static const std::string _flow_name;
    static const std::string _flow_type;
    static const std::string _device_id;
    static const std::string _operator;
    static const std::string _start_time;
    static const std::string _end_time;
    static const std::string _percent_complete;
    static const std::string _standard_hours;
    static const std::string _actual_hours;
    static const std::string _status;
    static const std::string _created_at;
    static const std::string _updated_at;
  };

  static const int primaryKeyNumber;
  static const std::string tableName;
  static const bool hasPrimaryKey;
  static const std::string primaryKeyName;
  using PrimaryKeyType = int32_t;
  const PrimaryKeyType &getPrimaryKey() const;

  /**
   * @brief constructor
   * @param r One row of records in the SQL query result.
   * @param indexOffset Set the offset to -1 to access all columns by column names,
   * otherwise access all columns by offsets.
   * @note If the SQL is not a style of 'select * from table_name ...' (select all
   * columns by an asterisk), please set the offset to -1.
   */
  explicit ProcessingFlows(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

  /**
   * @brief constructor
   * @param pJson The json object to construct a new instance.
   */
  explicit ProcessingFlows(const Json::Value &pJson) noexcept(false);

  /**
   * @brief constructor
   * @param pJson The json object to construct a new instance.
   * @param pMasqueradingVector The aliases of table columns.
   */
  ProcessingFlows(const Json::Value &pJson,
                  const std::vector<std::string> &pMasqueradingVector) noexcept(false);

  ProcessingFlows() = default;

  void updateByJson(const Json::Value &pJson) noexcept(false);
  void updateByMasqueradedJson(const Json::Value &pJson,
                               const std::vector<std::string> &pMasqueradingVector) noexcept(false);
  static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
  static bool validateMasqueradedJsonForCreation(
      const Json::Value &, const std::vector<std::string> &pMasqueradingVector, std::string &err);
  static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
  static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err);
  static bool validJsonOfField(size_t index, const std::string &fieldName, const Json::Value &pJson,
                               std::string &err, bool isForCreation);

  /**  For column id  */
  /// Get the value of the column id, returns the default value if the column is null
  const int32_t &getValueOfId() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<int32_t> &getId() const noexcept;
  /// Set the value of the column id
  void setId(const int32_t &pId) noexcept;

  /**  For column flow_name  */
  /// Get the value of the column flow_name, returns the default value if the column is null
  const std::string &getValueOfFlowName() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getFlowName() const noexcept;
  /// Set the value of the column flow_name
  void setFlowName(const std::string &pFlowName) noexcept;
  void setFlowName(std::string &&pFlowName) noexcept;

  /**  For column flow_type  */
  /// Get the value of the column flow_type, returns the default value if the column is null
  const std::string &getValueOfFlowType() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getFlowType() const noexcept;
  /// Set the value of the column flow_type
  void setFlowType(const std::string &pFlowType) noexcept;
  void setFlowType(std::string &&pFlowType) noexcept;

  /**  For column device_id  */
  /// Get the value of the column device_id, returns the default value if the column is null
  const int32_t &getValueOfDeviceId() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<int32_t> &getDeviceId() const noexcept;
  /// Set the value of the column device_id
  void setDeviceId(const int32_t &pDeviceId) noexcept;

  /**  For column operator  */
  /// Get the value of the column operator, returns the default value if the column is null
  const std::string &getValueOfOperator() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getOperator() const noexcept;
  /// Set the value of the column operator
  void setOperator(const std::string &pOperator) noexcept;
  void setOperator(std::string &&pOperator) noexcept;

  /**  For column start_time  */
  /// Get the value of the column start_time, returns the default value if the column is null
  const ::trantor::Date &getValueOfStartTime() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getStartTime() const noexcept;
  /// Set the value of the column start_time
  void setStartTime(const ::trantor::Date &pStartTime) noexcept;
  void setStartTimeToNull() noexcept;

  /**  For column end_time  */
  /// Get the value of the column end_time, returns the default value if the column is null
  const ::trantor::Date &getValueOfEndTime() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getEndTime() const noexcept;
  /// Set the value of the column end_time
  void setEndTime(const ::trantor::Date &pEndTime) noexcept;
  void setEndTimeToNull() noexcept;

  /**  For column percent_complete  */
  /// Get the value of the column percent_complete, returns the default value if the column is null
  const std::string &getValueOfPercentComplete() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getPercentComplete() const noexcept;
  /// Set the value of the column percent_complete
  void setPercentComplete(const std::string &pPercentComplete) noexcept;
  void setPercentComplete(std::string &&pPercentComplete) noexcept;

  /**  For column standard_hours  */
  /// Get the value of the column standard_hours, returns the default value if the column is null
  const std::string &getValueOfStandardHours() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getStandardHours() const noexcept;
  /// Set the value of the column standard_hours
  void setStandardHours(const std::string &pStandardHours) noexcept;
  void setStandardHours(std::string &&pStandardHours) noexcept;

  /**  For column actual_hours  */
  /// Get the value of the column actual_hours, returns the default value if the column is null
  const std::string &getValueOfActualHours() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getActualHours() const noexcept;
  /// Set the value of the column actual_hours
  void setActualHours(const std::string &pActualHours) noexcept;
  void setActualHours(std::string &&pActualHours) noexcept;
  void setActualHoursToNull() noexcept;

  /**  For column status  */
  /// Get the value of the column status, returns the default value if the column is null
  const std::string &getValueOfStatus() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getStatus() const noexcept;
  /// Set the value of the column status
  void setStatus(const std::string &pStatus) noexcept;
  void setStatus(std::string &&pStatus) noexcept;

  /**  For column created_at  */
  /// Get the value of the column created_at, returns the default value if the column is null
  const ::trantor::Date &getValueOfCreatedAt() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
  /// Set the value of the column created_at
  void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;

  /**  For column updated_at  */
  /// Get the value of the column updated_at, returns the default value if the column is null
  const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
  /// Set the value of the column updated_at
  void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;


  static size_t getColumnNumber() noexcept { return 13; }
  static const std::string &getColumnName(size_t index) noexcept(false);

  Json::Value toJson() const;
  Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
  /// Relationship interfaces
private:
  friend drogon::orm::Mapper<ProcessingFlows>;
  friend drogon::orm::BaseBuilder<ProcessingFlows, true, true>;
  friend drogon::orm::BaseBuilder<ProcessingFlows, true, false>;
  friend drogon::orm::BaseBuilder<ProcessingFlows, false, true>;
  friend drogon::orm::BaseBuilder<ProcessingFlows, false, false>;
#ifdef __cpp_impl_coroutine
  friend drogon::orm::CoroMapper<ProcessingFlows>;
#endif
  static const std::vector<std::string> &insertColumns() noexcept;
  void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
  const std::vector<std::string> updateColumns() const;
  void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
  /// For mysql or sqlite3
  void updateId(const uint64_t id);
  std::shared_ptr<int32_t> id_;
  std::shared_ptr<std::string> flowName_;
  std::shared_ptr<std::string> flowType_;
  std::shared_ptr<int32_t> deviceId_;
  std::shared_ptr<std::string> operator_;
  std::shared_ptr<::trantor::Date> startTime_;
  std::shared_ptr<::trantor::Date> endTime_;
  std::shared_ptr<std::string> percentComplete_;
  std::shared_ptr<std::string> standardHours_;
  std::shared_ptr<std::string> actualHours_;
  std::shared_ptr<std::string> status_;
  std::shared_ptr<::trantor::Date> createdAt_;
  std::shared_ptr<::trantor::Date> updatedAt_;
  struct MetaData {
    const std::string colName_;
    const std::string colType_;
    const std::string colDatabaseType_;
    const ssize_t colLength_;
    const bool isAutoVal_;
    const bool isPrimaryKey_;
    const bool notNull_;
  };
  static const std::vector<MetaData> metaData_;
  bool dirtyFlag_[13] = {false};

public:
  static const std::string &sqlForFindingByPrimaryKey() {
    static const std::string sql = "select * from " + tableName + " where id = $1";
    return sql;
  }

  static const std::string &sqlForDeletingByPrimaryKey() {
    static const std::string sql = "delete from " + tableName + " where id = $1";
    return sql;
  }
  std::string sqlForInserting(bool &needSelection) const {
    std::string sql = "insert into " + tableName + " (";
    size_t parametersCount = 0;
    needSelection = false;
    sql += "id,";
    ++parametersCount;
    if (dirtyFlag_[1]) {
      sql += "flow_name,";
      ++parametersCount;
    }
    if (dirtyFlag_[2]) {
      sql += "flow_type,";
      ++parametersCount;
    }
    if (dirtyFlag_[3]) {
      sql += "device_id,";
      ++parametersCount;
    }
    if (dirtyFlag_[4]) {
      sql += "operator,";
      ++parametersCount;
    }
    if (dirtyFlag_[5]) {
      sql += "start_time,";
      ++parametersCount;
    }
    if (dirtyFlag_[6]) {
      sql += "end_time,";
      ++parametersCount;
    }
    sql += "percent_complete,";
    ++parametersCount;
    if (!dirtyFlag_[7]) {
      needSelection = true;
    }
    if (dirtyFlag_[8]) {
      sql += "standard_hours,";
      ++parametersCount;
    }
    if (dirtyFlag_[9]) {
      sql += "actual_hours,";
      ++parametersCount;
    }
    if (dirtyFlag_[10]) {
      sql += "status,";
      ++parametersCount;
    }
    sql += "created_at,";
    ++parametersCount;
    if (!dirtyFlag_[11]) {
      needSelection = true;
    }
    sql += "updated_at,";
    ++parametersCount;
    if (!dirtyFlag_[12]) {
      needSelection = true;
    }
    needSelection = true;
    if (parametersCount > 0) {
      sql[sql.length() - 1] = ')';
      sql += " values (";
    } else
      sql += ") values (";

    int placeholder = 1;
    char placeholderStr[64];
    size_t n = 0;
    sql += "default,";
    if (dirtyFlag_[1]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[2]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[3]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[4]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[5]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[6]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[7]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    } else {
      sql += "default,";
    }
    if (dirtyFlag_[8]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[9]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[10]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[11]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    } else {
      sql += "default,";
    }
    if (dirtyFlag_[12]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    } else {
      sql += "default,";
    }
    if (parametersCount > 0) {
      sql.resize(sql.length() - 1);
    }
    if (needSelection) {
      sql.append(") returning *");
    } else {
      sql.append(1, ')');
    }
    LOG_TRACE << sql;
    return sql;
  }
};
} // namespace los_css_drogon
} // namespace drogon_model
