/**
 *
 *  QualityChecks.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "QualityChecks.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::los_css_drogon;

const std::string QualityChecks::Cols::_id = "\"id\"";
const std::string QualityChecks::Cols::_product_id = "\"product_id\"";
const std::string QualityChecks::Cols::_check_date = "\"check_date\"";
const std::string QualityChecks::Cols::_result = "\"result\"";
const std::string QualityChecks::Cols::_issue = "\"issue\"";
const std::string QualityChecks::Cols::_inspector = "\"inspector\"";
const std::string QualityChecks::Cols::_method = "\"method\"";
const std::string QualityChecks::Cols::_batch_number = "\"batch_number\"";
const std::string QualityChecks::Cols::_production_date = "\"production_date\"";
const std::string QualityChecks::Cols::_report_data = "\"report_data\"";
const std::string QualityChecks::Cols::_check_status = "\"check_status\"";
const std::string QualityChecks::Cols::_created_at = "\"created_at\"";
const std::string QualityChecks::Cols::_updated_at = "\"updated_at\"";
const std::string QualityChecks::primaryKeyName = "id";
const bool QualityChecks::hasPrimaryKey = true;
const std::string QualityChecks::tableName = "\"quality_checks\"";

const std::vector<typename QualityChecks::MetaData> QualityChecks::metaData_ = {
    {"id", "int32_t", "integer", 4, 1, 1, 1},
    {"product_id", "std::string", "character varying", 64, 0, 0, 1},
    {"check_date", "::trantor::Date", "date", 0, 0, 0, 1},
    {"result", "std::string", "character varying", 16, 0, 0, 1},
    {"issue", "std::string", "text", 0, 0, 0, 0},
    {"inspector", "std::string", "character varying", 64, 0, 0, 1},
    {"method", "std::string", "character varying", 16, 0, 0, 1},
    {"batch_number", "std::string", "character varying", 64, 0, 0, 1},
    {"production_date", "::trantor::Date", "date", 0, 0, 0, 1},
    {"report_data", "std::string", "text", 0, 0, 0, 0},
    {"check_status", "std::string", "character varying", 16, 0, 0, 1},
    {"created_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1},
    {"updated_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1}};
const std::string &QualityChecks::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
QualityChecks::QualityChecks(const Row &r, const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["id"].isNull()) {
      id_ = std::make_shared<int32_t>(r["id"].as<int32_t>());
    }
    if (!r["product_id"].isNull()) {
      productId_ = std::make_shared<std::string>(r["product_id"].as<std::string>());
    }
    if (!r["check_date"].isNull()) {
      auto daysStr = r["check_date"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      checkDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
    if (!r["result"].isNull()) {
      result_ = std::make_shared<std::string>(r["result"].as<std::string>());
    }
    if (!r["issue"].isNull()) {
      issue_ = std::make_shared<std::string>(r["issue"].as<std::string>());
    }
    if (!r["inspector"].isNull()) {
      inspector_ = std::make_shared<std::string>(r["inspector"].as<std::string>());
    }
    if (!r["method"].isNull()) {
      method_ = std::make_shared<std::string>(r["method"].as<std::string>());
    }
    if (!r["batch_number"].isNull()) {
      batchNumber_ = std::make_shared<std::string>(r["batch_number"].as<std::string>());
    }
    if (!r["production_date"].isNull()) {
      auto daysStr = r["production_date"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      productionDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
    if (!r["report_data"].isNull()) {
      reportData_ = std::make_shared<std::string>(r["report_data"].as<std::string>());
    }
    if (!r["check_status"].isNull()) {
      checkStatus_ = std::make_shared<std::string>(r["check_status"].as<std::string>());
    }
    if (!r["created_at"].isNull()) {
      auto timeStr = r["created_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    if (!r["updated_at"].isNull()) {
      auto timeStr = r["updated_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 13 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      id_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      productId_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 2;
    if (!r[index].isNull()) {
      auto daysStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      checkDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
    index = offset + 3;
    if (!r[index].isNull()) {
      result_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 4;
    if (!r[index].isNull()) {
      issue_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 5;
    if (!r[index].isNull()) {
      inspector_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 6;
    if (!r[index].isNull()) {
      method_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 7;
    if (!r[index].isNull()) {
      batchNumber_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 8;
    if (!r[index].isNull()) {
      auto daysStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      productionDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
    index = offset + 9;
    if (!r[index].isNull()) {
      reportData_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 10;
    if (!r[index].isNull()) {
      checkStatus_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 11;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    index = offset + 12;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

QualityChecks::QualityChecks(const Json::Value &pJson,
                             const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 13) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      productId_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      auto daysStr = pJson[pMasqueradingVector[2]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      checkDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      result_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      issue_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      inspector_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      method_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      batchNumber_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      auto daysStr = pJson[pMasqueradingVector[8]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      productionDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
    dirtyFlag_[9] = true;
    if (!pJson[pMasqueradingVector[9]].isNull()) {
      reportData_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
    }
  }
  if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
    dirtyFlag_[10] = true;
    if (!pJson[pMasqueradingVector[10]].isNull()) {
      checkStatus_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
    }
  }
  if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
    dirtyFlag_[11] = true;
    if (!pJson[pMasqueradingVector[11]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[11]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
    dirtyFlag_[12] = true;
    if (!pJson[pMasqueradingVector[12]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[12]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

QualityChecks::QualityChecks(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    dirtyFlag_[0] = true;
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("product_id")) {
    dirtyFlag_[1] = true;
    if (!pJson["product_id"].isNull()) {
      productId_ = std::make_shared<std::string>(pJson["product_id"].asString());
    }
  }
  if (pJson.isMember("check_date")) {
    dirtyFlag_[2] = true;
    if (!pJson["check_date"].isNull()) {
      auto daysStr = pJson["check_date"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      checkDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (pJson.isMember("result")) {
    dirtyFlag_[3] = true;
    if (!pJson["result"].isNull()) {
      result_ = std::make_shared<std::string>(pJson["result"].asString());
    }
  }
  if (pJson.isMember("issue")) {
    dirtyFlag_[4] = true;
    if (!pJson["issue"].isNull()) {
      issue_ = std::make_shared<std::string>(pJson["issue"].asString());
    }
  }
  if (pJson.isMember("inspector")) {
    dirtyFlag_[5] = true;
    if (!pJson["inspector"].isNull()) {
      inspector_ = std::make_shared<std::string>(pJson["inspector"].asString());
    }
  }
  if (pJson.isMember("method")) {
    dirtyFlag_[6] = true;
    if (!pJson["method"].isNull()) {
      method_ = std::make_shared<std::string>(pJson["method"].asString());
    }
  }
  if (pJson.isMember("batch_number")) {
    dirtyFlag_[7] = true;
    if (!pJson["batch_number"].isNull()) {
      batchNumber_ = std::make_shared<std::string>(pJson["batch_number"].asString());
    }
  }
  if (pJson.isMember("production_date")) {
    dirtyFlag_[8] = true;
    if (!pJson["production_date"].isNull()) {
      auto daysStr = pJson["production_date"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      productionDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (pJson.isMember("report_data")) {
    dirtyFlag_[9] = true;
    if (!pJson["report_data"].isNull()) {
      reportData_ = std::make_shared<std::string>(pJson["report_data"].asString());
    }
  }
  if (pJson.isMember("check_status")) {
    dirtyFlag_[10] = true;
    if (!pJson["check_status"].isNull()) {
      checkStatus_ = std::make_shared<std::string>(pJson["check_status"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[11] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[12] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void QualityChecks::updateByMasqueradedJson(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 13) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      productId_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      auto daysStr = pJson[pMasqueradingVector[2]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      checkDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      result_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      issue_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      inspector_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      method_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      batchNumber_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      auto daysStr = pJson[pMasqueradingVector[8]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      productionDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
    dirtyFlag_[9] = true;
    if (!pJson[pMasqueradingVector[9]].isNull()) {
      reportData_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
    }
  }
  if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
    dirtyFlag_[10] = true;
    if (!pJson[pMasqueradingVector[10]].isNull()) {
      checkStatus_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
    }
  }
  if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
    dirtyFlag_[11] = true;
    if (!pJson[pMasqueradingVector[11]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[11]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
    dirtyFlag_[12] = true;
    if (!pJson[pMasqueradingVector[12]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[12]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void QualityChecks::updateByJson(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("product_id")) {
    dirtyFlag_[1] = true;
    if (!pJson["product_id"].isNull()) {
      productId_ = std::make_shared<std::string>(pJson["product_id"].asString());
    }
  }
  if (pJson.isMember("check_date")) {
    dirtyFlag_[2] = true;
    if (!pJson["check_date"].isNull()) {
      auto daysStr = pJson["check_date"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      checkDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (pJson.isMember("result")) {
    dirtyFlag_[3] = true;
    if (!pJson["result"].isNull()) {
      result_ = std::make_shared<std::string>(pJson["result"].asString());
    }
  }
  if (pJson.isMember("issue")) {
    dirtyFlag_[4] = true;
    if (!pJson["issue"].isNull()) {
      issue_ = std::make_shared<std::string>(pJson["issue"].asString());
    }
  }
  if (pJson.isMember("inspector")) {
    dirtyFlag_[5] = true;
    if (!pJson["inspector"].isNull()) {
      inspector_ = std::make_shared<std::string>(pJson["inspector"].asString());
    }
  }
  if (pJson.isMember("method")) {
    dirtyFlag_[6] = true;
    if (!pJson["method"].isNull()) {
      method_ = std::make_shared<std::string>(pJson["method"].asString());
    }
  }
  if (pJson.isMember("batch_number")) {
    dirtyFlag_[7] = true;
    if (!pJson["batch_number"].isNull()) {
      batchNumber_ = std::make_shared<std::string>(pJson["batch_number"].asString());
    }
  }
  if (pJson.isMember("production_date")) {
    dirtyFlag_[8] = true;
    if (!pJson["production_date"].isNull()) {
      auto daysStr = pJson["production_date"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      productionDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (pJson.isMember("report_data")) {
    dirtyFlag_[9] = true;
    if (!pJson["report_data"].isNull()) {
      reportData_ = std::make_shared<std::string>(pJson["report_data"].asString());
    }
  }
  if (pJson.isMember("check_status")) {
    dirtyFlag_[10] = true;
    if (!pJson["check_status"].isNull()) {
      checkStatus_ = std::make_shared<std::string>(pJson["check_status"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[11] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[12] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

const int32_t &QualityChecks::getValueOfId() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (id_)
    return *id_;
  return defaultValue;
}
const std::shared_ptr<int32_t> &QualityChecks::getId() const noexcept { return id_; }
void QualityChecks::setId(const int32_t &pId) noexcept {
  id_ = std::make_shared<int32_t>(pId);
  dirtyFlag_[0] = true;
}
const typename QualityChecks::PrimaryKeyType &QualityChecks::getPrimaryKey() const {
  assert(id_);
  return *id_;
}

const std::string &QualityChecks::getValueOfProductId() const noexcept {
  static const std::string defaultValue = std::string();
  if (productId_)
    return *productId_;
  return defaultValue;
}
const std::shared_ptr<std::string> &QualityChecks::getProductId() const noexcept {
  return productId_;
}
void QualityChecks::setProductId(const std::string &pProductId) noexcept {
  productId_ = std::make_shared<std::string>(pProductId);
  dirtyFlag_[1] = true;
}
void QualityChecks::setProductId(std::string &&pProductId) noexcept {
  productId_ = std::make_shared<std::string>(std::move(pProductId));
  dirtyFlag_[1] = true;
}

const ::trantor::Date &QualityChecks::getValueOfCheckDate() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (checkDate_)
    return *checkDate_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &QualityChecks::getCheckDate() const noexcept {
  return checkDate_;
}
void QualityChecks::setCheckDate(const ::trantor::Date &pCheckDate) noexcept {
  checkDate_ = std::make_shared<::trantor::Date>(pCheckDate.roundDay());
  dirtyFlag_[2] = true;
}

const std::string &QualityChecks::getValueOfResult() const noexcept {
  static const std::string defaultValue = std::string();
  if (result_)
    return *result_;
  return defaultValue;
}
const std::shared_ptr<std::string> &QualityChecks::getResult() const noexcept { return result_; }
void QualityChecks::setResult(const std::string &pResult) noexcept {
  result_ = std::make_shared<std::string>(pResult);
  dirtyFlag_[3] = true;
}
void QualityChecks::setResult(std::string &&pResult) noexcept {
  result_ = std::make_shared<std::string>(std::move(pResult));
  dirtyFlag_[3] = true;
}

const std::string &QualityChecks::getValueOfIssue() const noexcept {
  static const std::string defaultValue = std::string();
  if (issue_)
    return *issue_;
  return defaultValue;
}
const std::shared_ptr<std::string> &QualityChecks::getIssue() const noexcept { return issue_; }
void QualityChecks::setIssue(const std::string &pIssue) noexcept {
  issue_ = std::make_shared<std::string>(pIssue);
  dirtyFlag_[4] = true;
}
void QualityChecks::setIssue(std::string &&pIssue) noexcept {
  issue_ = std::make_shared<std::string>(std::move(pIssue));
  dirtyFlag_[4] = true;
}
void QualityChecks::setIssueToNull() noexcept {
  issue_.reset();
  dirtyFlag_[4] = true;
}

const std::string &QualityChecks::getValueOfInspector() const noexcept {
  static const std::string defaultValue = std::string();
  if (inspector_)
    return *inspector_;
  return defaultValue;
}
const std::shared_ptr<std::string> &QualityChecks::getInspector() const noexcept {
  return inspector_;
}
void QualityChecks::setInspector(const std::string &pInspector) noexcept {
  inspector_ = std::make_shared<std::string>(pInspector);
  dirtyFlag_[5] = true;
}
void QualityChecks::setInspector(std::string &&pInspector) noexcept {
  inspector_ = std::make_shared<std::string>(std::move(pInspector));
  dirtyFlag_[5] = true;
}

const std::string &QualityChecks::getValueOfMethod() const noexcept {
  static const std::string defaultValue = std::string();
  if (method_)
    return *method_;
  return defaultValue;
}
const std::shared_ptr<std::string> &QualityChecks::getMethod() const noexcept { return method_; }
void QualityChecks::setMethod(const std::string &pMethod) noexcept {
  method_ = std::make_shared<std::string>(pMethod);
  dirtyFlag_[6] = true;
}
void QualityChecks::setMethod(std::string &&pMethod) noexcept {
  method_ = std::make_shared<std::string>(std::move(pMethod));
  dirtyFlag_[6] = true;
}

const std::string &QualityChecks::getValueOfBatchNumber() const noexcept {
  static const std::string defaultValue = std::string();
  if (batchNumber_)
    return *batchNumber_;
  return defaultValue;
}
const std::shared_ptr<std::string> &QualityChecks::getBatchNumber() const noexcept {
  return batchNumber_;
}
void QualityChecks::setBatchNumber(const std::string &pBatchNumber) noexcept {
  batchNumber_ = std::make_shared<std::string>(pBatchNumber);
  dirtyFlag_[7] = true;
}
void QualityChecks::setBatchNumber(std::string &&pBatchNumber) noexcept {
  batchNumber_ = std::make_shared<std::string>(std::move(pBatchNumber));
  dirtyFlag_[7] = true;
}

const ::trantor::Date &QualityChecks::getValueOfProductionDate() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (productionDate_)
    return *productionDate_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &QualityChecks::getProductionDate() const noexcept {
  return productionDate_;
}
void QualityChecks::setProductionDate(const ::trantor::Date &pProductionDate) noexcept {
  productionDate_ = std::make_shared<::trantor::Date>(pProductionDate.roundDay());
  dirtyFlag_[8] = true;
}

const std::string &QualityChecks::getValueOfReportData() const noexcept {
  static const std::string defaultValue = std::string();
  if (reportData_)
    return *reportData_;
  return defaultValue;
}
const std::shared_ptr<std::string> &QualityChecks::getReportData() const noexcept {
  return reportData_;
}
void QualityChecks::setReportData(const std::string &pReportData) noexcept {
  reportData_ = std::make_shared<std::string>(pReportData);
  dirtyFlag_[9] = true;
}
void QualityChecks::setReportData(std::string &&pReportData) noexcept {
  reportData_ = std::make_shared<std::string>(std::move(pReportData));
  dirtyFlag_[9] = true;
}
void QualityChecks::setReportDataToNull() noexcept {
  reportData_.reset();
  dirtyFlag_[9] = true;
}

const std::string &QualityChecks::getValueOfCheckStatus() const noexcept {
  static const std::string defaultValue = std::string();
  if (checkStatus_)
    return *checkStatus_;
  return defaultValue;
}
const std::shared_ptr<std::string> &QualityChecks::getCheckStatus() const noexcept {
  return checkStatus_;
}
void QualityChecks::setCheckStatus(const std::string &pCheckStatus) noexcept {
  checkStatus_ = std::make_shared<std::string>(pCheckStatus);
  dirtyFlag_[10] = true;
}
void QualityChecks::setCheckStatus(std::string &&pCheckStatus) noexcept {
  checkStatus_ = std::make_shared<std::string>(std::move(pCheckStatus));
  dirtyFlag_[10] = true;
}

const ::trantor::Date &QualityChecks::getValueOfCreatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (createdAt_)
    return *createdAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &QualityChecks::getCreatedAt() const noexcept {
  return createdAt_;
}
void QualityChecks::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept {
  createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
  dirtyFlag_[11] = true;
}

const ::trantor::Date &QualityChecks::getValueOfUpdatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (updatedAt_)
    return *updatedAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &QualityChecks::getUpdatedAt() const noexcept {
  return updatedAt_;
}
void QualityChecks::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept {
  updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
  dirtyFlag_[12] = true;
}

void QualityChecks::updateId(const uint64_t id) {}

const std::vector<std::string> &QualityChecks::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {
      "product_id",   "check_date",      "result",      "issue",        "inspector",  "method",
      "batch_number", "production_date", "report_data", "check_status", "created_at", "updated_at"};
  return inCols;
}

void QualityChecks::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getProductId()) {
      binder << getValueOfProductId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getCheckDate()) {
      binder << getValueOfCheckDate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getResult()) {
      binder << getValueOfResult();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getIssue()) {
      binder << getValueOfIssue();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getInspector()) {
      binder << getValueOfInspector();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getMethod()) {
      binder << getValueOfMethod();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getBatchNumber()) {
      binder << getValueOfBatchNumber();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getProductionDate()) {
      binder << getValueOfProductionDate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[9]) {
    if (getReportData()) {
      binder << getValueOfReportData();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[10]) {
    if (getCheckStatus()) {
      binder << getValueOfCheckStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[11]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[12]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> QualityChecks::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  if (dirtyFlag_[2]) {
    ret.push_back(getColumnName(2));
  }
  if (dirtyFlag_[3]) {
    ret.push_back(getColumnName(3));
  }
  if (dirtyFlag_[4]) {
    ret.push_back(getColumnName(4));
  }
  if (dirtyFlag_[5]) {
    ret.push_back(getColumnName(5));
  }
  if (dirtyFlag_[6]) {
    ret.push_back(getColumnName(6));
  }
  if (dirtyFlag_[7]) {
    ret.push_back(getColumnName(7));
  }
  if (dirtyFlag_[8]) {
    ret.push_back(getColumnName(8));
  }
  if (dirtyFlag_[9]) {
    ret.push_back(getColumnName(9));
  }
  if (dirtyFlag_[10]) {
    ret.push_back(getColumnName(10));
  }
  if (dirtyFlag_[11]) {
    ret.push_back(getColumnName(11));
  }
  if (dirtyFlag_[12]) {
    ret.push_back(getColumnName(12));
  }
  return ret;
}

void QualityChecks::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getProductId()) {
      binder << getValueOfProductId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getCheckDate()) {
      binder << getValueOfCheckDate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getResult()) {
      binder << getValueOfResult();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getIssue()) {
      binder << getValueOfIssue();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getInspector()) {
      binder << getValueOfInspector();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getMethod()) {
      binder << getValueOfMethod();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getBatchNumber()) {
      binder << getValueOfBatchNumber();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getProductionDate()) {
      binder << getValueOfProductionDate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[9]) {
    if (getReportData()) {
      binder << getValueOfReportData();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[10]) {
    if (getCheckStatus()) {
      binder << getValueOfCheckStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[11]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[12]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value QualityChecks::toJson() const {
  Json::Value ret;
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getProductId()) {
    ret["product_id"] = getValueOfProductId();
  } else {
    ret["product_id"] = Json::Value();
  }
  if (getCheckDate()) {
    ret["check_date"] = getCheckDate()->toDbStringLocal();
  } else {
    ret["check_date"] = Json::Value();
  }
  if (getResult()) {
    ret["result"] = getValueOfResult();
  } else {
    ret["result"] = Json::Value();
  }
  if (getIssue()) {
    ret["issue"] = getValueOfIssue();
  } else {
    ret["issue"] = Json::Value();
  }
  if (getInspector()) {
    ret["inspector"] = getValueOfInspector();
  } else {
    ret["inspector"] = Json::Value();
  }
  if (getMethod()) {
    ret["method"] = getValueOfMethod();
  } else {
    ret["method"] = Json::Value();
  }
  if (getBatchNumber()) {
    ret["batch_number"] = getValueOfBatchNumber();
  } else {
    ret["batch_number"] = Json::Value();
  }
  if (getProductionDate()) {
    ret["production_date"] = getProductionDate()->toDbStringLocal();
  } else {
    ret["production_date"] = Json::Value();
  }
  if (getReportData()) {
    ret["report_data"] = getValueOfReportData();
  } else {
    ret["report_data"] = Json::Value();
  }
  if (getCheckStatus()) {
    ret["check_status"] = getValueOfCheckStatus();
  } else {
    ret["check_status"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

Json::Value
QualityChecks::toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 13) {
    if (!pMasqueradingVector[0].empty()) {
      if (getId()) {
        ret[pMasqueradingVector[0]] = getValueOfId();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getProductId()) {
        ret[pMasqueradingVector[1]] = getValueOfProductId();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (getCheckDate()) {
        ret[pMasqueradingVector[2]] = getCheckDate()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[2]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (getResult()) {
        ret[pMasqueradingVector[3]] = getValueOfResult();
      } else {
        ret[pMasqueradingVector[3]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (getIssue()) {
        ret[pMasqueradingVector[4]] = getValueOfIssue();
      } else {
        ret[pMasqueradingVector[4]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (getInspector()) {
        ret[pMasqueradingVector[5]] = getValueOfInspector();
      } else {
        ret[pMasqueradingVector[5]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (getMethod()) {
        ret[pMasqueradingVector[6]] = getValueOfMethod();
      } else {
        ret[pMasqueradingVector[6]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (getBatchNumber()) {
        ret[pMasqueradingVector[7]] = getValueOfBatchNumber();
      } else {
        ret[pMasqueradingVector[7]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (getProductionDate()) {
        ret[pMasqueradingVector[8]] = getProductionDate()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[8]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[9].empty()) {
      if (getReportData()) {
        ret[pMasqueradingVector[9]] = getValueOfReportData();
      } else {
        ret[pMasqueradingVector[9]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[10].empty()) {
      if (getCheckStatus()) {
        ret[pMasqueradingVector[10]] = getValueOfCheckStatus();
      } else {
        ret[pMasqueradingVector[10]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[11].empty()) {
      if (getCreatedAt()) {
        ret[pMasqueradingVector[11]] = getCreatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[11]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[12].empty()) {
      if (getUpdatedAt()) {
        ret[pMasqueradingVector[12]] = getUpdatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[12]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getProductId()) {
    ret["product_id"] = getValueOfProductId();
  } else {
    ret["product_id"] = Json::Value();
  }
  if (getCheckDate()) {
    ret["check_date"] = getCheckDate()->toDbStringLocal();
  } else {
    ret["check_date"] = Json::Value();
  }
  if (getResult()) {
    ret["result"] = getValueOfResult();
  } else {
    ret["result"] = Json::Value();
  }
  if (getIssue()) {
    ret["issue"] = getValueOfIssue();
  } else {
    ret["issue"] = Json::Value();
  }
  if (getInspector()) {
    ret["inspector"] = getValueOfInspector();
  } else {
    ret["inspector"] = Json::Value();
  }
  if (getMethod()) {
    ret["method"] = getValueOfMethod();
  } else {
    ret["method"] = Json::Value();
  }
  if (getBatchNumber()) {
    ret["batch_number"] = getValueOfBatchNumber();
  } else {
    ret["batch_number"] = Json::Value();
  }
  if (getProductionDate()) {
    ret["production_date"] = getProductionDate()->toDbStringLocal();
  } else {
    ret["production_date"] = Json::Value();
  }
  if (getReportData()) {
    ret["report_data"] = getValueOfReportData();
  } else {
    ret["report_data"] = Json::Value();
  }
  if (getCheckStatus()) {
    ret["check_status"] = getValueOfCheckStatus();
  } else {
    ret["check_status"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

bool QualityChecks::validateJsonForCreation(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, true))
      return false;
  }
  if (pJson.isMember("product_id")) {
    if (!validJsonOfField(1, "product_id", pJson["product_id"], err, true))
      return false;
  } else {
    err = "The product_id column cannot be null";
    return false;
  }
  if (pJson.isMember("check_date")) {
    if (!validJsonOfField(2, "check_date", pJson["check_date"], err, true))
      return false;
  } else {
    err = "The check_date column cannot be null";
    return false;
  }
  if (pJson.isMember("result")) {
    if (!validJsonOfField(3, "result", pJson["result"], err, true))
      return false;
  } else {
    err = "The result column cannot be null";
    return false;
  }
  if (pJson.isMember("issue")) {
    if (!validJsonOfField(4, "issue", pJson["issue"], err, true))
      return false;
  }
  if (pJson.isMember("inspector")) {
    if (!validJsonOfField(5, "inspector", pJson["inspector"], err, true))
      return false;
  } else {
    err = "The inspector column cannot be null";
    return false;
  }
  if (pJson.isMember("method")) {
    if (!validJsonOfField(6, "method", pJson["method"], err, true))
      return false;
  } else {
    err = "The method column cannot be null";
    return false;
  }
  if (pJson.isMember("batch_number")) {
    if (!validJsonOfField(7, "batch_number", pJson["batch_number"], err, true))
      return false;
  } else {
    err = "The batch_number column cannot be null";
    return false;
  }
  if (pJson.isMember("production_date")) {
    if (!validJsonOfField(8, "production_date", pJson["production_date"], err, true))
      return false;
  } else {
    err = "The production_date column cannot be null";
    return false;
  }
  if (pJson.isMember("report_data")) {
    if (!validJsonOfField(9, "report_data", pJson["report_data"], err, true))
      return false;
  }
  if (pJson.isMember("check_status")) {
    if (!validJsonOfField(10, "check_status", pJson["check_status"], err, true))
      return false;
  } else {
    err = "The check_status column cannot be null";
    return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(11, "created_at", pJson["created_at"], err, true))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(12, "updated_at", pJson["updated_at"], err, true))
      return false;
  }
  return true;
}
bool QualityChecks::validateMasqueradedJsonForCreation(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 13) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[1] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (pJson.isMember(pMasqueradingVector[2])) {
        if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[2] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (pJson.isMember(pMasqueradingVector[3])) {
        if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[3] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (pJson.isMember(pMasqueradingVector[4])) {
        if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (pJson.isMember(pMasqueradingVector[5])) {
        if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[5] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (pJson.isMember(pMasqueradingVector[6])) {
        if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[6] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (pJson.isMember(pMasqueradingVector[7])) {
        if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[7] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (pJson.isMember(pMasqueradingVector[8])) {
        if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[8] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[9].empty()) {
      if (pJson.isMember(pMasqueradingVector[9])) {
        if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[10].empty()) {
      if (pJson.isMember(pMasqueradingVector[10])) {
        if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err,
                              true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[10] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[11].empty()) {
      if (pJson.isMember(pMasqueradingVector[11])) {
        if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err,
                              true))
          return false;
      }
    }
    if (!pMasqueradingVector[12].empty()) {
      if (pJson.isMember(pMasqueradingVector[12])) {
        if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err,
                              true))
          return false;
      }
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool QualityChecks::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, false))
      return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("product_id")) {
    if (!validJsonOfField(1, "product_id", pJson["product_id"], err, false))
      return false;
  }
  if (pJson.isMember("check_date")) {
    if (!validJsonOfField(2, "check_date", pJson["check_date"], err, false))
      return false;
  }
  if (pJson.isMember("result")) {
    if (!validJsonOfField(3, "result", pJson["result"], err, false))
      return false;
  }
  if (pJson.isMember("issue")) {
    if (!validJsonOfField(4, "issue", pJson["issue"], err, false))
      return false;
  }
  if (pJson.isMember("inspector")) {
    if (!validJsonOfField(5, "inspector", pJson["inspector"], err, false))
      return false;
  }
  if (pJson.isMember("method")) {
    if (!validJsonOfField(6, "method", pJson["method"], err, false))
      return false;
  }
  if (pJson.isMember("batch_number")) {
    if (!validJsonOfField(7, "batch_number", pJson["batch_number"], err, false))
      return false;
  }
  if (pJson.isMember("production_date")) {
    if (!validJsonOfField(8, "production_date", pJson["production_date"], err, false))
      return false;
  }
  if (pJson.isMember("report_data")) {
    if (!validJsonOfField(9, "report_data", pJson["report_data"], err, false))
      return false;
  }
  if (pJson.isMember("check_status")) {
    if (!validJsonOfField(10, "check_status", pJson["check_status"], err, false))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(11, "created_at", pJson["created_at"], err, false))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(12, "updated_at", pJson["updated_at"], err, false))
      return false;
  }
  return true;
}
bool QualityChecks::validateMasqueradedJsonForUpdate(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 13) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err = "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
        return false;
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
      if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
        return false;
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
      if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
        return false;
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
      if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
        return false;
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
      if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
        return false;
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
      if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
        return false;
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
      if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
        return false;
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
      if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
        return false;
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
      if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
        return false;
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
      if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err,
                            false))
        return false;
    }
    if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
      if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err,
                            false))
        return false;
    }
    if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
      if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err,
                            false))
        return false;
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool QualityChecks::validJsonOfField(size_t index, const std::string &fieldName,
                                     const Json::Value &pJson, std::string &err,
                                     bool isForCreation) {
  switch (index) {
  case 0:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (isForCreation) {
      err = "The automatic primary key cannot be set";
      return false;
    }
    if (!pJson.isInt()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 1:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 64) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 64)";
      return false;
    }

    break;
  case 2:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 3:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 4:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 5:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 64) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 64)";
      return false;
    }

    break;
  case 6:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 7:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 64) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 64)";
      return false;
    }

    break;
  case 8:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 9:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 10:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 11:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 12:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  default:
    err = "Internal error in the server";
    return false;
  }
  return true;
}
