/**
 *
 *  RawMaterialIns.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "RawMaterialIns.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::los_css_drogon;

const std::string RawMaterialIns::Cols::_id = "\"id\"";
const std::string RawMaterialIns::Cols::_material_type = "\"material_type\"";
const std::string RawMaterialIns::Cols::_batch_number = "\"batch_number\"";
const std::string RawMaterialIns::Cols::_supplier_name = "\"supplier_name\"";
const std::string RawMaterialIns::Cols::_in_date = "\"in_date\"";
const std::string RawMaterialIns::Cols::_quantity = "\"quantity\"";
const std::string RawMaterialIns::Cols::_unit = "\"unit\"";
const std::string RawMaterialIns::Cols::_quality_level = "\"quality_level\"";
const std::string RawMaterialIns::Cols::_storage_location = "\"storage_location\"";
const std::string RawMaterialIns::Cols::_inspection_no = "\"inspection_no\"";
const std::string RawMaterialIns::Cols::_status = "\"status\"";
const std::string RawMaterialIns::Cols::_operator = "\"operator\"";
const std::string RawMaterialIns::Cols::_created_at = "\"created_at\"";
const std::string RawMaterialIns::Cols::_updated_at = "\"updated_at\"";
const std::string RawMaterialIns::primaryKeyName = "id";
const bool RawMaterialIns::hasPrimaryKey = true;
const std::string RawMaterialIns::tableName = "\"raw_material_ins\"";

const std::vector<typename RawMaterialIns::MetaData> RawMaterialIns::metaData_ = {
    {"id", "int32_t", "integer", 4, 1, 1, 1},
    {"material_type", "std::string", "character varying", 16, 0, 0, 1},
    {"batch_number", "std::string", "character varying", 64, 0, 0, 1},
    {"supplier_name", "std::string", "character varying", 128, 0, 0, 1},
    {"in_date", "::trantor::Date", "date", 0, 0, 0, 1},
    {"quantity", "std::string", "numeric", 0, 0, 0, 1},
    {"unit", "std::string", "character varying", 16, 0, 0, 1},
    {"quality_level", "std::string", "character varying", 16, 0, 0, 1},
    {"storage_location", "std::string", "character varying", 128, 0, 0, 1},
    {"inspection_no", "std::string", "character varying", 64, 0, 0, 0},
    {"status", "std::string", "character varying", 16, 0, 0, 1},
    {"operator", "std::string", "character varying", 64, 0, 0, 1},
    {"created_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1},
    {"updated_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1}};
const std::string &RawMaterialIns::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
RawMaterialIns::RawMaterialIns(const Row &r, const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["id"].isNull()) {
      id_ = std::make_shared<int32_t>(r["id"].as<int32_t>());
    }
    if (!r["material_type"].isNull()) {
      materialType_ = std::make_shared<std::string>(r["material_type"].as<std::string>());
    }
    if (!r["batch_number"].isNull()) {
      batchNumber_ = std::make_shared<std::string>(r["batch_number"].as<std::string>());
    }
    if (!r["supplier_name"].isNull()) {
      supplierName_ = std::make_shared<std::string>(r["supplier_name"].as<std::string>());
    }
    if (!r["in_date"].isNull()) {
      auto daysStr = r["in_date"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      inDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
    if (!r["quantity"].isNull()) {
      quantity_ = std::make_shared<std::string>(r["quantity"].as<std::string>());
    }
    if (!r["unit"].isNull()) {
      unit_ = std::make_shared<std::string>(r["unit"].as<std::string>());
    }
    if (!r["quality_level"].isNull()) {
      qualityLevel_ = std::make_shared<std::string>(r["quality_level"].as<std::string>());
    }
    if (!r["storage_location"].isNull()) {
      storageLocation_ = std::make_shared<std::string>(r["storage_location"].as<std::string>());
    }
    if (!r["inspection_no"].isNull()) {
      inspectionNo_ = std::make_shared<std::string>(r["inspection_no"].as<std::string>());
    }
    if (!r["status"].isNull()) {
      status_ = std::make_shared<std::string>(r["status"].as<std::string>());
    }
    if (!r["operator"].isNull()) {
      operator_ = std::make_shared<std::string>(r["operator"].as<std::string>());
    }
    if (!r["created_at"].isNull()) {
      auto timeStr = r["created_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    if (!r["updated_at"].isNull()) {
      auto timeStr = r["updated_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 14 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      id_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      materialType_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 2;
    if (!r[index].isNull()) {
      batchNumber_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 3;
    if (!r[index].isNull()) {
      supplierName_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 4;
    if (!r[index].isNull()) {
      auto daysStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      inDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
    index = offset + 5;
    if (!r[index].isNull()) {
      quantity_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 6;
    if (!r[index].isNull()) {
      unit_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 7;
    if (!r[index].isNull()) {
      qualityLevel_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 8;
    if (!r[index].isNull()) {
      storageLocation_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 9;
    if (!r[index].isNull()) {
      inspectionNo_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 10;
    if (!r[index].isNull()) {
      status_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 11;
    if (!r[index].isNull()) {
      operator_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 12;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    index = offset + 13;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

RawMaterialIns::RawMaterialIns(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 14) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      materialType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      batchNumber_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      supplierName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      auto daysStr = pJson[pMasqueradingVector[4]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      inDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      quantity_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      unit_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      qualityLevel_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      storageLocation_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
    }
  }
  if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
    dirtyFlag_[9] = true;
    if (!pJson[pMasqueradingVector[9]].isNull()) {
      inspectionNo_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
    }
  }
  if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
    dirtyFlag_[10] = true;
    if (!pJson[pMasqueradingVector[10]].isNull()) {
      status_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
    }
  }
  if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
    dirtyFlag_[11] = true;
    if (!pJson[pMasqueradingVector[11]].isNull()) {
      operator_ = std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
    }
  }
  if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
    dirtyFlag_[12] = true;
    if (!pJson[pMasqueradingVector[12]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[12]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13])) {
    dirtyFlag_[13] = true;
    if (!pJson[pMasqueradingVector[13]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[13]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

RawMaterialIns::RawMaterialIns(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    dirtyFlag_[0] = true;
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("material_type")) {
    dirtyFlag_[1] = true;
    if (!pJson["material_type"].isNull()) {
      materialType_ = std::make_shared<std::string>(pJson["material_type"].asString());
    }
  }
  if (pJson.isMember("batch_number")) {
    dirtyFlag_[2] = true;
    if (!pJson["batch_number"].isNull()) {
      batchNumber_ = std::make_shared<std::string>(pJson["batch_number"].asString());
    }
  }
  if (pJson.isMember("supplier_name")) {
    dirtyFlag_[3] = true;
    if (!pJson["supplier_name"].isNull()) {
      supplierName_ = std::make_shared<std::string>(pJson["supplier_name"].asString());
    }
  }
  if (pJson.isMember("in_date")) {
    dirtyFlag_[4] = true;
    if (!pJson["in_date"].isNull()) {
      auto daysStr = pJson["in_date"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      inDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (pJson.isMember("quantity")) {
    dirtyFlag_[5] = true;
    if (!pJson["quantity"].isNull()) {
      quantity_ = std::make_shared<std::string>(pJson["quantity"].asString());
    }
  }
  if (pJson.isMember("unit")) {
    dirtyFlag_[6] = true;
    if (!pJson["unit"].isNull()) {
      unit_ = std::make_shared<std::string>(pJson["unit"].asString());
    }
  }
  if (pJson.isMember("quality_level")) {
    dirtyFlag_[7] = true;
    if (!pJson["quality_level"].isNull()) {
      qualityLevel_ = std::make_shared<std::string>(pJson["quality_level"].asString());
    }
  }
  if (pJson.isMember("storage_location")) {
    dirtyFlag_[8] = true;
    if (!pJson["storage_location"].isNull()) {
      storageLocation_ = std::make_shared<std::string>(pJson["storage_location"].asString());
    }
  }
  if (pJson.isMember("inspection_no")) {
    dirtyFlag_[9] = true;
    if (!pJson["inspection_no"].isNull()) {
      inspectionNo_ = std::make_shared<std::string>(pJson["inspection_no"].asString());
    }
  }
  if (pJson.isMember("status")) {
    dirtyFlag_[10] = true;
    if (!pJson["status"].isNull()) {
      status_ = std::make_shared<std::string>(pJson["status"].asString());
    }
  }
  if (pJson.isMember("operator")) {
    dirtyFlag_[11] = true;
    if (!pJson["operator"].isNull()) {
      operator_ = std::make_shared<std::string>(pJson["operator"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[12] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[13] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void RawMaterialIns::updateByMasqueradedJson(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 14) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      materialType_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      batchNumber_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      supplierName_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      auto daysStr = pJson[pMasqueradingVector[4]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      inDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      quantity_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      unit_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      qualityLevel_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      storageLocation_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
    }
  }
  if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
    dirtyFlag_[9] = true;
    if (!pJson[pMasqueradingVector[9]].isNull()) {
      inspectionNo_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
    }
  }
  if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
    dirtyFlag_[10] = true;
    if (!pJson[pMasqueradingVector[10]].isNull()) {
      status_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
    }
  }
  if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
    dirtyFlag_[11] = true;
    if (!pJson[pMasqueradingVector[11]].isNull()) {
      operator_ = std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
    }
  }
  if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
    dirtyFlag_[12] = true;
    if (!pJson[pMasqueradingVector[12]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[12]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13])) {
    dirtyFlag_[13] = true;
    if (!pJson[pMasqueradingVector[13]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[13]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void RawMaterialIns::updateByJson(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("material_type")) {
    dirtyFlag_[1] = true;
    if (!pJson["material_type"].isNull()) {
      materialType_ = std::make_shared<std::string>(pJson["material_type"].asString());
    }
  }
  if (pJson.isMember("batch_number")) {
    dirtyFlag_[2] = true;
    if (!pJson["batch_number"].isNull()) {
      batchNumber_ = std::make_shared<std::string>(pJson["batch_number"].asString());
    }
  }
  if (pJson.isMember("supplier_name")) {
    dirtyFlag_[3] = true;
    if (!pJson["supplier_name"].isNull()) {
      supplierName_ = std::make_shared<std::string>(pJson["supplier_name"].asString());
    }
  }
  if (pJson.isMember("in_date")) {
    dirtyFlag_[4] = true;
    if (!pJson["in_date"].isNull()) {
      auto daysStr = pJson["in_date"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      inDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (pJson.isMember("quantity")) {
    dirtyFlag_[5] = true;
    if (!pJson["quantity"].isNull()) {
      quantity_ = std::make_shared<std::string>(pJson["quantity"].asString());
    }
  }
  if (pJson.isMember("unit")) {
    dirtyFlag_[6] = true;
    if (!pJson["unit"].isNull()) {
      unit_ = std::make_shared<std::string>(pJson["unit"].asString());
    }
  }
  if (pJson.isMember("quality_level")) {
    dirtyFlag_[7] = true;
    if (!pJson["quality_level"].isNull()) {
      qualityLevel_ = std::make_shared<std::string>(pJson["quality_level"].asString());
    }
  }
  if (pJson.isMember("storage_location")) {
    dirtyFlag_[8] = true;
    if (!pJson["storage_location"].isNull()) {
      storageLocation_ = std::make_shared<std::string>(pJson["storage_location"].asString());
    }
  }
  if (pJson.isMember("inspection_no")) {
    dirtyFlag_[9] = true;
    if (!pJson["inspection_no"].isNull()) {
      inspectionNo_ = std::make_shared<std::string>(pJson["inspection_no"].asString());
    }
  }
  if (pJson.isMember("status")) {
    dirtyFlag_[10] = true;
    if (!pJson["status"].isNull()) {
      status_ = std::make_shared<std::string>(pJson["status"].asString());
    }
  }
  if (pJson.isMember("operator")) {
    dirtyFlag_[11] = true;
    if (!pJson["operator"].isNull()) {
      operator_ = std::make_shared<std::string>(pJson["operator"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[12] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[13] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

const int32_t &RawMaterialIns::getValueOfId() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (id_)
    return *id_;
  return defaultValue;
}
const std::shared_ptr<int32_t> &RawMaterialIns::getId() const noexcept { return id_; }
void RawMaterialIns::setId(const int32_t &pId) noexcept {
  id_ = std::make_shared<int32_t>(pId);
  dirtyFlag_[0] = true;
}
const typename RawMaterialIns::PrimaryKeyType &RawMaterialIns::getPrimaryKey() const {
  assert(id_);
  return *id_;
}

const std::string &RawMaterialIns::getValueOfMaterialType() const noexcept {
  static const std::string defaultValue = std::string();
  if (materialType_)
    return *materialType_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getMaterialType() const noexcept {
  return materialType_;
}
void RawMaterialIns::setMaterialType(const std::string &pMaterialType) noexcept {
  materialType_ = std::make_shared<std::string>(pMaterialType);
  dirtyFlag_[1] = true;
}
void RawMaterialIns::setMaterialType(std::string &&pMaterialType) noexcept {
  materialType_ = std::make_shared<std::string>(std::move(pMaterialType));
  dirtyFlag_[1] = true;
}

const std::string &RawMaterialIns::getValueOfBatchNumber() const noexcept {
  static const std::string defaultValue = std::string();
  if (batchNumber_)
    return *batchNumber_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getBatchNumber() const noexcept {
  return batchNumber_;
}
void RawMaterialIns::setBatchNumber(const std::string &pBatchNumber) noexcept {
  batchNumber_ = std::make_shared<std::string>(pBatchNumber);
  dirtyFlag_[2] = true;
}
void RawMaterialIns::setBatchNumber(std::string &&pBatchNumber) noexcept {
  batchNumber_ = std::make_shared<std::string>(std::move(pBatchNumber));
  dirtyFlag_[2] = true;
}

const std::string &RawMaterialIns::getValueOfSupplierName() const noexcept {
  static const std::string defaultValue = std::string();
  if (supplierName_)
    return *supplierName_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getSupplierName() const noexcept {
  return supplierName_;
}
void RawMaterialIns::setSupplierName(const std::string &pSupplierName) noexcept {
  supplierName_ = std::make_shared<std::string>(pSupplierName);
  dirtyFlag_[3] = true;
}
void RawMaterialIns::setSupplierName(std::string &&pSupplierName) noexcept {
  supplierName_ = std::make_shared<std::string>(std::move(pSupplierName));
  dirtyFlag_[3] = true;
}

const ::trantor::Date &RawMaterialIns::getValueOfInDate() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (inDate_)
    return *inDate_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &RawMaterialIns::getInDate() const noexcept {
  return inDate_;
}
void RawMaterialIns::setInDate(const ::trantor::Date &pInDate) noexcept {
  inDate_ = std::make_shared<::trantor::Date>(pInDate.roundDay());
  dirtyFlag_[4] = true;
}

const std::string &RawMaterialIns::getValueOfQuantity() const noexcept {
  static const std::string defaultValue = std::string();
  if (quantity_)
    return *quantity_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getQuantity() const noexcept {
  return quantity_;
}
void RawMaterialIns::setQuantity(const std::string &pQuantity) noexcept {
  quantity_ = std::make_shared<std::string>(pQuantity);
  dirtyFlag_[5] = true;
}
void RawMaterialIns::setQuantity(std::string &&pQuantity) noexcept {
  quantity_ = std::make_shared<std::string>(std::move(pQuantity));
  dirtyFlag_[5] = true;
}

const std::string &RawMaterialIns::getValueOfUnit() const noexcept {
  static const std::string defaultValue = std::string();
  if (unit_)
    return *unit_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getUnit() const noexcept { return unit_; }
void RawMaterialIns::setUnit(const std::string &pUnit) noexcept {
  unit_ = std::make_shared<std::string>(pUnit);
  dirtyFlag_[6] = true;
}
void RawMaterialIns::setUnit(std::string &&pUnit) noexcept {
  unit_ = std::make_shared<std::string>(std::move(pUnit));
  dirtyFlag_[6] = true;
}

const std::string &RawMaterialIns::getValueOfQualityLevel() const noexcept {
  static const std::string defaultValue = std::string();
  if (qualityLevel_)
    return *qualityLevel_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getQualityLevel() const noexcept {
  return qualityLevel_;
}
void RawMaterialIns::setQualityLevel(const std::string &pQualityLevel) noexcept {
  qualityLevel_ = std::make_shared<std::string>(pQualityLevel);
  dirtyFlag_[7] = true;
}
void RawMaterialIns::setQualityLevel(std::string &&pQualityLevel) noexcept {
  qualityLevel_ = std::make_shared<std::string>(std::move(pQualityLevel));
  dirtyFlag_[7] = true;
}

const std::string &RawMaterialIns::getValueOfStorageLocation() const noexcept {
  static const std::string defaultValue = std::string();
  if (storageLocation_)
    return *storageLocation_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getStorageLocation() const noexcept {
  return storageLocation_;
}
void RawMaterialIns::setStorageLocation(const std::string &pStorageLocation) noexcept {
  storageLocation_ = std::make_shared<std::string>(pStorageLocation);
  dirtyFlag_[8] = true;
}
void RawMaterialIns::setStorageLocation(std::string &&pStorageLocation) noexcept {
  storageLocation_ = std::make_shared<std::string>(std::move(pStorageLocation));
  dirtyFlag_[8] = true;
}

const std::string &RawMaterialIns::getValueOfInspectionNo() const noexcept {
  static const std::string defaultValue = std::string();
  if (inspectionNo_)
    return *inspectionNo_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getInspectionNo() const noexcept {
  return inspectionNo_;
}
void RawMaterialIns::setInspectionNo(const std::string &pInspectionNo) noexcept {
  inspectionNo_ = std::make_shared<std::string>(pInspectionNo);
  dirtyFlag_[9] = true;
}
void RawMaterialIns::setInspectionNo(std::string &&pInspectionNo) noexcept {
  inspectionNo_ = std::make_shared<std::string>(std::move(pInspectionNo));
  dirtyFlag_[9] = true;
}
void RawMaterialIns::setInspectionNoToNull() noexcept {
  inspectionNo_.reset();
  dirtyFlag_[9] = true;
}

const std::string &RawMaterialIns::getValueOfStatus() const noexcept {
  static const std::string defaultValue = std::string();
  if (status_)
    return *status_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getStatus() const noexcept { return status_; }
void RawMaterialIns::setStatus(const std::string &pStatus) noexcept {
  status_ = std::make_shared<std::string>(pStatus);
  dirtyFlag_[10] = true;
}
void RawMaterialIns::setStatus(std::string &&pStatus) noexcept {
  status_ = std::make_shared<std::string>(std::move(pStatus));
  dirtyFlag_[10] = true;
}

const std::string &RawMaterialIns::getValueOfOperator() const noexcept {
  static const std::string defaultValue = std::string();
  if (operator_)
    return *operator_;
  return defaultValue;
}
const std::shared_ptr<std::string> &RawMaterialIns::getOperator() const noexcept {
  return operator_;
}
void RawMaterialIns::setOperator(const std::string &pOperator) noexcept {
  operator_ = std::make_shared<std::string>(pOperator);
  dirtyFlag_[11] = true;
}
void RawMaterialIns::setOperator(std::string &&pOperator) noexcept {
  operator_ = std::make_shared<std::string>(std::move(pOperator));
  dirtyFlag_[11] = true;
}

const ::trantor::Date &RawMaterialIns::getValueOfCreatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (createdAt_)
    return *createdAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &RawMaterialIns::getCreatedAt() const noexcept {
  return createdAt_;
}
void RawMaterialIns::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept {
  createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
  dirtyFlag_[12] = true;
}

const ::trantor::Date &RawMaterialIns::getValueOfUpdatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (updatedAt_)
    return *updatedAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &RawMaterialIns::getUpdatedAt() const noexcept {
  return updatedAt_;
}
void RawMaterialIns::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept {
  updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
  dirtyFlag_[13] = true;
}

void RawMaterialIns::updateId(const uint64_t id) {}

const std::vector<std::string> &RawMaterialIns::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {
      "material_type", "batch_number",  "supplier_name",    "in_date",       "quantity",
      "unit",          "quality_level", "storage_location", "inspection_no", "status",
      "operator",      "created_at",    "updated_at"};
  return inCols;
}

void RawMaterialIns::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getMaterialType()) {
      binder << getValueOfMaterialType();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getBatchNumber()) {
      binder << getValueOfBatchNumber();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getSupplierName()) {
      binder << getValueOfSupplierName();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getInDate()) {
      binder << getValueOfInDate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getQuantity()) {
      binder << getValueOfQuantity();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getUnit()) {
      binder << getValueOfUnit();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getQualityLevel()) {
      binder << getValueOfQualityLevel();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getStorageLocation()) {
      binder << getValueOfStorageLocation();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[9]) {
    if (getInspectionNo()) {
      binder << getValueOfInspectionNo();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[10]) {
    if (getStatus()) {
      binder << getValueOfStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[11]) {
    if (getOperator()) {
      binder << getValueOfOperator();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[12]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[13]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> RawMaterialIns::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  if (dirtyFlag_[2]) {
    ret.push_back(getColumnName(2));
  }
  if (dirtyFlag_[3]) {
    ret.push_back(getColumnName(3));
  }
  if (dirtyFlag_[4]) {
    ret.push_back(getColumnName(4));
  }
  if (dirtyFlag_[5]) {
    ret.push_back(getColumnName(5));
  }
  if (dirtyFlag_[6]) {
    ret.push_back(getColumnName(6));
  }
  if (dirtyFlag_[7]) {
    ret.push_back(getColumnName(7));
  }
  if (dirtyFlag_[8]) {
    ret.push_back(getColumnName(8));
  }
  if (dirtyFlag_[9]) {
    ret.push_back(getColumnName(9));
  }
  if (dirtyFlag_[10]) {
    ret.push_back(getColumnName(10));
  }
  if (dirtyFlag_[11]) {
    ret.push_back(getColumnName(11));
  }
  if (dirtyFlag_[12]) {
    ret.push_back(getColumnName(12));
  }
  if (dirtyFlag_[13]) {
    ret.push_back(getColumnName(13));
  }
  return ret;
}

void RawMaterialIns::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getMaterialType()) {
      binder << getValueOfMaterialType();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getBatchNumber()) {
      binder << getValueOfBatchNumber();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getSupplierName()) {
      binder << getValueOfSupplierName();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getInDate()) {
      binder << getValueOfInDate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getQuantity()) {
      binder << getValueOfQuantity();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getUnit()) {
      binder << getValueOfUnit();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getQualityLevel()) {
      binder << getValueOfQualityLevel();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getStorageLocation()) {
      binder << getValueOfStorageLocation();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[9]) {
    if (getInspectionNo()) {
      binder << getValueOfInspectionNo();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[10]) {
    if (getStatus()) {
      binder << getValueOfStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[11]) {
    if (getOperator()) {
      binder << getValueOfOperator();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[12]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[13]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value RawMaterialIns::toJson() const {
  Json::Value ret;
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getMaterialType()) {
    ret["material_type"] = getValueOfMaterialType();
  } else {
    ret["material_type"] = Json::Value();
  }
  if (getBatchNumber()) {
    ret["batch_number"] = getValueOfBatchNumber();
  } else {
    ret["batch_number"] = Json::Value();
  }
  if (getSupplierName()) {
    ret["supplier_name"] = getValueOfSupplierName();
  } else {
    ret["supplier_name"] = Json::Value();
  }
  if (getInDate()) {
    ret["in_date"] = getInDate()->toDbStringLocal();
  } else {
    ret["in_date"] = Json::Value();
  }
  if (getQuantity()) {
    ret["quantity"] = getValueOfQuantity();
  } else {
    ret["quantity"] = Json::Value();
  }
  if (getUnit()) {
    ret["unit"] = getValueOfUnit();
  } else {
    ret["unit"] = Json::Value();
  }
  if (getQualityLevel()) {
    ret["quality_level"] = getValueOfQualityLevel();
  } else {
    ret["quality_level"] = Json::Value();
  }
  if (getStorageLocation()) {
    ret["storage_location"] = getValueOfStorageLocation();
  } else {
    ret["storage_location"] = Json::Value();
  }
  if (getInspectionNo()) {
    ret["inspection_no"] = getValueOfInspectionNo();
  } else {
    ret["inspection_no"] = Json::Value();
  }
  if (getStatus()) {
    ret["status"] = getValueOfStatus();
  } else {
    ret["status"] = Json::Value();
  }
  if (getOperator()) {
    ret["operator"] = getValueOfOperator();
  } else {
    ret["operator"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

Json::Value
RawMaterialIns::toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 14) {
    if (!pMasqueradingVector[0].empty()) {
      if (getId()) {
        ret[pMasqueradingVector[0]] = getValueOfId();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getMaterialType()) {
        ret[pMasqueradingVector[1]] = getValueOfMaterialType();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (getBatchNumber()) {
        ret[pMasqueradingVector[2]] = getValueOfBatchNumber();
      } else {
        ret[pMasqueradingVector[2]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (getSupplierName()) {
        ret[pMasqueradingVector[3]] = getValueOfSupplierName();
      } else {
        ret[pMasqueradingVector[3]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (getInDate()) {
        ret[pMasqueradingVector[4]] = getInDate()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[4]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (getQuantity()) {
        ret[pMasqueradingVector[5]] = getValueOfQuantity();
      } else {
        ret[pMasqueradingVector[5]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (getUnit()) {
        ret[pMasqueradingVector[6]] = getValueOfUnit();
      } else {
        ret[pMasqueradingVector[6]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (getQualityLevel()) {
        ret[pMasqueradingVector[7]] = getValueOfQualityLevel();
      } else {
        ret[pMasqueradingVector[7]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (getStorageLocation()) {
        ret[pMasqueradingVector[8]] = getValueOfStorageLocation();
      } else {
        ret[pMasqueradingVector[8]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[9].empty()) {
      if (getInspectionNo()) {
        ret[pMasqueradingVector[9]] = getValueOfInspectionNo();
      } else {
        ret[pMasqueradingVector[9]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[10].empty()) {
      if (getStatus()) {
        ret[pMasqueradingVector[10]] = getValueOfStatus();
      } else {
        ret[pMasqueradingVector[10]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[11].empty()) {
      if (getOperator()) {
        ret[pMasqueradingVector[11]] = getValueOfOperator();
      } else {
        ret[pMasqueradingVector[11]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[12].empty()) {
      if (getCreatedAt()) {
        ret[pMasqueradingVector[12]] = getCreatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[12]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[13].empty()) {
      if (getUpdatedAt()) {
        ret[pMasqueradingVector[13]] = getUpdatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[13]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getMaterialType()) {
    ret["material_type"] = getValueOfMaterialType();
  } else {
    ret["material_type"] = Json::Value();
  }
  if (getBatchNumber()) {
    ret["batch_number"] = getValueOfBatchNumber();
  } else {
    ret["batch_number"] = Json::Value();
  }
  if (getSupplierName()) {
    ret["supplier_name"] = getValueOfSupplierName();
  } else {
    ret["supplier_name"] = Json::Value();
  }
  if (getInDate()) {
    ret["in_date"] = getInDate()->toDbStringLocal();
  } else {
    ret["in_date"] = Json::Value();
  }
  if (getQuantity()) {
    ret["quantity"] = getValueOfQuantity();
  } else {
    ret["quantity"] = Json::Value();
  }
  if (getUnit()) {
    ret["unit"] = getValueOfUnit();
  } else {
    ret["unit"] = Json::Value();
  }
  if (getQualityLevel()) {
    ret["quality_level"] = getValueOfQualityLevel();
  } else {
    ret["quality_level"] = Json::Value();
  }
  if (getStorageLocation()) {
    ret["storage_location"] = getValueOfStorageLocation();
  } else {
    ret["storage_location"] = Json::Value();
  }
  if (getInspectionNo()) {
    ret["inspection_no"] = getValueOfInspectionNo();
  } else {
    ret["inspection_no"] = Json::Value();
  }
  if (getStatus()) {
    ret["status"] = getValueOfStatus();
  } else {
    ret["status"] = Json::Value();
  }
  if (getOperator()) {
    ret["operator"] = getValueOfOperator();
  } else {
    ret["operator"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

bool RawMaterialIns::validateJsonForCreation(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, true))
      return false;
  }
  if (pJson.isMember("material_type")) {
    if (!validJsonOfField(1, "material_type", pJson["material_type"], err, true))
      return false;
  } else {
    err = "The material_type column cannot be null";
    return false;
  }
  if (pJson.isMember("batch_number")) {
    if (!validJsonOfField(2, "batch_number", pJson["batch_number"], err, true))
      return false;
  } else {
    err = "The batch_number column cannot be null";
    return false;
  }
  if (pJson.isMember("supplier_name")) {
    if (!validJsonOfField(3, "supplier_name", pJson["supplier_name"], err, true))
      return false;
  } else {
    err = "The supplier_name column cannot be null";
    return false;
  }
  if (pJson.isMember("in_date")) {
    if (!validJsonOfField(4, "in_date", pJson["in_date"], err, true))
      return false;
  } else {
    err = "The in_date column cannot be null";
    return false;
  }
  if (pJson.isMember("quantity")) {
    if (!validJsonOfField(5, "quantity", pJson["quantity"], err, true))
      return false;
  } else {
    err = "The quantity column cannot be null";
    return false;
  }
  if (pJson.isMember("unit")) {
    if (!validJsonOfField(6, "unit", pJson["unit"], err, true))
      return false;
  } else {
    err = "The unit column cannot be null";
    return false;
  }
  if (pJson.isMember("quality_level")) {
    if (!validJsonOfField(7, "quality_level", pJson["quality_level"], err, true))
      return false;
  } else {
    err = "The quality_level column cannot be null";
    return false;
  }
  if (pJson.isMember("storage_location")) {
    if (!validJsonOfField(8, "storage_location", pJson["storage_location"], err, true))
      return false;
  } else {
    err = "The storage_location column cannot be null";
    return false;
  }
  if (pJson.isMember("inspection_no")) {
    if (!validJsonOfField(9, "inspection_no", pJson["inspection_no"], err, true))
      return false;
  }
  if (pJson.isMember("status")) {
    if (!validJsonOfField(10, "status", pJson["status"], err, true))
      return false;
  } else {
    err = "The status column cannot be null";
    return false;
  }
  if (pJson.isMember("operator")) {
    if (!validJsonOfField(11, "operator", pJson["operator"], err, true))
      return false;
  } else {
    err = "The operator column cannot be null";
    return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(12, "created_at", pJson["created_at"], err, true))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(13, "updated_at", pJson["updated_at"], err, true))
      return false;
  }
  return true;
}
bool RawMaterialIns::validateMasqueradedJsonForCreation(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 14) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[1] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (pJson.isMember(pMasqueradingVector[2])) {
        if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[2] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (pJson.isMember(pMasqueradingVector[3])) {
        if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[3] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (pJson.isMember(pMasqueradingVector[4])) {
        if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[4] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (pJson.isMember(pMasqueradingVector[5])) {
        if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[5] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (pJson.isMember(pMasqueradingVector[6])) {
        if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[6] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (pJson.isMember(pMasqueradingVector[7])) {
        if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[7] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (pJson.isMember(pMasqueradingVector[8])) {
        if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[8] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[9].empty()) {
      if (pJson.isMember(pMasqueradingVector[9])) {
        if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[10].empty()) {
      if (pJson.isMember(pMasqueradingVector[10])) {
        if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err,
                              true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[10] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[11].empty()) {
      if (pJson.isMember(pMasqueradingVector[11])) {
        if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err,
                              true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[11] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[12].empty()) {
      if (pJson.isMember(pMasqueradingVector[12])) {
        if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err,
                              true))
          return false;
      }
    }
    if (!pMasqueradingVector[13].empty()) {
      if (pJson.isMember(pMasqueradingVector[13])) {
        if (!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err,
                              true))
          return false;
      }
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool RawMaterialIns::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, false))
      return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("material_type")) {
    if (!validJsonOfField(1, "material_type", pJson["material_type"], err, false))
      return false;
  }
  if (pJson.isMember("batch_number")) {
    if (!validJsonOfField(2, "batch_number", pJson["batch_number"], err, false))
      return false;
  }
  if (pJson.isMember("supplier_name")) {
    if (!validJsonOfField(3, "supplier_name", pJson["supplier_name"], err, false))
      return false;
  }
  if (pJson.isMember("in_date")) {
    if (!validJsonOfField(4, "in_date", pJson["in_date"], err, false))
      return false;
  }
  if (pJson.isMember("quantity")) {
    if (!validJsonOfField(5, "quantity", pJson["quantity"], err, false))
      return false;
  }
  if (pJson.isMember("unit")) {
    if (!validJsonOfField(6, "unit", pJson["unit"], err, false))
      return false;
  }
  if (pJson.isMember("quality_level")) {
    if (!validJsonOfField(7, "quality_level", pJson["quality_level"], err, false))
      return false;
  }
  if (pJson.isMember("storage_location")) {
    if (!validJsonOfField(8, "storage_location", pJson["storage_location"], err, false))
      return false;
  }
  if (pJson.isMember("inspection_no")) {
    if (!validJsonOfField(9, "inspection_no", pJson["inspection_no"], err, false))
      return false;
  }
  if (pJson.isMember("status")) {
    if (!validJsonOfField(10, "status", pJson["status"], err, false))
      return false;
  }
  if (pJson.isMember("operator")) {
    if (!validJsonOfField(11, "operator", pJson["operator"], err, false))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(12, "created_at", pJson["created_at"], err, false))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(13, "updated_at", pJson["updated_at"], err, false))
      return false;
  }
  return true;
}
bool RawMaterialIns::validateMasqueradedJsonForUpdate(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 14) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err = "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
        return false;
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
      if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
        return false;
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
      if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
        return false;
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
      if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
        return false;
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
      if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
        return false;
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
      if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
        return false;
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
      if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
        return false;
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
      if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
        return false;
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
      if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
        return false;
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
      if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err,
                            false))
        return false;
    }
    if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
      if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err,
                            false))
        return false;
    }
    if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
      if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err,
                            false))
        return false;
    }
    if (!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13])) {
      if (!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err,
                            false))
        return false;
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool RawMaterialIns::validJsonOfField(size_t index, const std::string &fieldName,
                                      const Json::Value &pJson, std::string &err,
                                      bool isForCreation) {
  switch (index) {
  case 0:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (isForCreation) {
      err = "The automatic primary key cannot be set";
      return false;
    }
    if (!pJson.isInt()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 1:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 2:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 64) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 64)";
      return false;
    }

    break;
  case 3:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 128) {
      err =
          "String length exceeds limit for the " + fieldName + " field (the maximum value is 128)";
      return false;
    }

    break;
  case 4:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 5:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 6:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 7:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 8:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 128) {
      err =
          "String length exceeds limit for the " + fieldName + " field (the maximum value is 128)";
      return false;
    }

    break;
  case 9:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 64) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 64)";
      return false;
    }

    break;
  case 10:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 11:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 64) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 64)";
      return false;
    }

    break;
  case 12:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 13:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  default:
    err = "Internal error in the server";
    return false;
  }
  return true;
}
