/**
 *
 *  RawMaterialIns.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/BaseBuilder.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <iostream>
#include <json/json.h>
#include <memory>
#include <stdint.h>
#include <string>
#include <string_view>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <tuple>
#include <vector>

namespace drogon {
namespace orm {
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
} // namespace orm
} // namespace drogon
namespace drogon_model {
namespace los_css_drogon {

class RawMaterialIns {
public:
  struct Cols {
    static const std::string _id;
    static const std::string _material_type;
    static const std::string _batch_number;
    static const std::string _supplier_name;
    static const std::string _in_date;
    static const std::string _quantity;
    static const std::string _unit;
    static const std::string _quality_level;
    static const std::string _storage_location;
    static const std::string _inspection_no;
    static const std::string _status;
    static const std::string _operator;
    static const std::string _created_at;
    static const std::string _updated_at;
  };

  static const int primaryKeyNumber;
  static const std::string tableName;
  static const bool hasPrimaryKey;
  static const std::string primaryKeyName;
  using PrimaryKeyType = int32_t;
  const PrimaryKeyType &getPrimaryKey() const;

  /**
   * @brief constructor
   * @param r One row of records in the SQL query result.
   * @param indexOffset Set the offset to -1 to access all columns by column names,
   * otherwise access all columns by offsets.
   * @note If the SQL is not a style of 'select * from table_name ...' (select all
   * columns by an asterisk), please set the offset to -1.
   */
  explicit RawMaterialIns(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

  /**
   * @brief constructor
   * @param pJson The json object to construct a new instance.
   */
  explicit RawMaterialIns(const Json::Value &pJson) noexcept(false);

  /**
   * @brief constructor
   * @param pJson The json object to construct a new instance.
   * @param pMasqueradingVector The aliases of table columns.
   */
  RawMaterialIns(const Json::Value &pJson,
                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);

  RawMaterialIns() = default;

  void updateByJson(const Json::Value &pJson) noexcept(false);
  void updateByMasqueradedJson(const Json::Value &pJson,
                               const std::vector<std::string> &pMasqueradingVector) noexcept(false);
  static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
  static bool validateMasqueradedJsonForCreation(
      const Json::Value &, const std::vector<std::string> &pMasqueradingVector, std::string &err);
  static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
  static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err);
  static bool validJsonOfField(size_t index, const std::string &fieldName, const Json::Value &pJson,
                               std::string &err, bool isForCreation);

  /**  For column id  */
  /// Get the value of the column id, returns the default value if the column is null
  const int32_t &getValueOfId() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<int32_t> &getId() const noexcept;
  /// Set the value of the column id
  void setId(const int32_t &pId) noexcept;

  /**  For column material_type  */
  /// Get the value of the column material_type, returns the default value if the column is null
  const std::string &getValueOfMaterialType() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getMaterialType() const noexcept;
  /// Set the value of the column material_type
  void setMaterialType(const std::string &pMaterialType) noexcept;
  void setMaterialType(std::string &&pMaterialType) noexcept;

  /**  For column batch_number  */
  /// Get the value of the column batch_number, returns the default value if the column is null
  const std::string &getValueOfBatchNumber() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getBatchNumber() const noexcept;
  /// Set the value of the column batch_number
  void setBatchNumber(const std::string &pBatchNumber) noexcept;
  void setBatchNumber(std::string &&pBatchNumber) noexcept;

  /**  For column supplier_name  */
  /// Get the value of the column supplier_name, returns the default value if the column is null
  const std::string &getValueOfSupplierName() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getSupplierName() const noexcept;
  /// Set the value of the column supplier_name
  void setSupplierName(const std::string &pSupplierName) noexcept;
  void setSupplierName(std::string &&pSupplierName) noexcept;

  /**  For column in_date  */
  /// Get the value of the column in_date, returns the default value if the column is null
  const ::trantor::Date &getValueOfInDate() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getInDate() const noexcept;
  /// Set the value of the column in_date
  void setInDate(const ::trantor::Date &pInDate) noexcept;

  /**  For column quantity  */
  /// Get the value of the column quantity, returns the default value if the column is null
  const std::string &getValueOfQuantity() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getQuantity() const noexcept;
  /// Set the value of the column quantity
  void setQuantity(const std::string &pQuantity) noexcept;
  void setQuantity(std::string &&pQuantity) noexcept;

  /**  For column unit  */
  /// Get the value of the column unit, returns the default value if the column is null
  const std::string &getValueOfUnit() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getUnit() const noexcept;
  /// Set the value of the column unit
  void setUnit(const std::string &pUnit) noexcept;
  void setUnit(std::string &&pUnit) noexcept;

  /**  For column quality_level  */
  /// Get the value of the column quality_level, returns the default value if the column is null
  const std::string &getValueOfQualityLevel() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getQualityLevel() const noexcept;
  /// Set the value of the column quality_level
  void setQualityLevel(const std::string &pQualityLevel) noexcept;
  void setQualityLevel(std::string &&pQualityLevel) noexcept;

  /**  For column storage_location  */
  /// Get the value of the column storage_location, returns the default value if the column is null
  const std::string &getValueOfStorageLocation() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getStorageLocation() const noexcept;
  /// Set the value of the column storage_location
  void setStorageLocation(const std::string &pStorageLocation) noexcept;
  void setStorageLocation(std::string &&pStorageLocation) noexcept;

  /**  For column inspection_no  */
  /// Get the value of the column inspection_no, returns the default value if the column is null
  const std::string &getValueOfInspectionNo() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getInspectionNo() const noexcept;
  /// Set the value of the column inspection_no
  void setInspectionNo(const std::string &pInspectionNo) noexcept;
  void setInspectionNo(std::string &&pInspectionNo) noexcept;
  void setInspectionNoToNull() noexcept;

  /**  For column status  */
  /// Get the value of the column status, returns the default value if the column is null
  const std::string &getValueOfStatus() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getStatus() const noexcept;
  /// Set the value of the column status
  void setStatus(const std::string &pStatus) noexcept;
  void setStatus(std::string &&pStatus) noexcept;

  /**  For column operator  */
  /// Get the value of the column operator, returns the default value if the column is null
  const std::string &getValueOfOperator() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<std::string> &getOperator() const noexcept;
  /// Set the value of the column operator
  void setOperator(const std::string &pOperator) noexcept;
  void setOperator(std::string &&pOperator) noexcept;

  /**  For column created_at  */
  /// Get the value of the column created_at, returns the default value if the column is null
  const ::trantor::Date &getValueOfCreatedAt() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
  /// Set the value of the column created_at
  void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;

  /**  For column updated_at  */
  /// Get the value of the column updated_at, returns the default value if the column is null
  const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
  /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object
  /// if the column is null
  const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
  /// Set the value of the column updated_at
  void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;


  static size_t getColumnNumber() noexcept { return 14; }
  static const std::string &getColumnName(size_t index) noexcept(false);

  Json::Value toJson() const;
  Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
  /// Relationship interfaces
private:
  friend drogon::orm::Mapper<RawMaterialIns>;
  friend drogon::orm::BaseBuilder<RawMaterialIns, true, true>;
  friend drogon::orm::BaseBuilder<RawMaterialIns, true, false>;
  friend drogon::orm::BaseBuilder<RawMaterialIns, false, true>;
  friend drogon::orm::BaseBuilder<RawMaterialIns, false, false>;
#ifdef __cpp_impl_coroutine
  friend drogon::orm::CoroMapper<RawMaterialIns>;
#endif
  static const std::vector<std::string> &insertColumns() noexcept;
  void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
  const std::vector<std::string> updateColumns() const;
  void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
  /// For mysql or sqlite3
  void updateId(const uint64_t id);
  std::shared_ptr<int32_t> id_;
  std::shared_ptr<std::string> materialType_;
  std::shared_ptr<std::string> batchNumber_;
  std::shared_ptr<std::string> supplierName_;
  std::shared_ptr<::trantor::Date> inDate_;
  std::shared_ptr<std::string> quantity_;
  std::shared_ptr<std::string> unit_;
  std::shared_ptr<std::string> qualityLevel_;
  std::shared_ptr<std::string> storageLocation_;
  std::shared_ptr<std::string> inspectionNo_;
  std::shared_ptr<std::string> status_;
  std::shared_ptr<std::string> operator_;
  std::shared_ptr<::trantor::Date> createdAt_;
  std::shared_ptr<::trantor::Date> updatedAt_;
  struct MetaData {
    const std::string colName_;
    const std::string colType_;
    const std::string colDatabaseType_;
    const ssize_t colLength_;
    const bool isAutoVal_;
    const bool isPrimaryKey_;
    const bool notNull_;
  };
  static const std::vector<MetaData> metaData_;
  bool dirtyFlag_[14] = {false};

public:
  static const std::string &sqlForFindingByPrimaryKey() {
    static const std::string sql = "select * from " + tableName + " where id = $1";
    return sql;
  }

  static const std::string &sqlForDeletingByPrimaryKey() {
    static const std::string sql = "delete from " + tableName + " where id = $1";
    return sql;
  }
  std::string sqlForInserting(bool &needSelection) const {
    std::string sql = "insert into " + tableName + " (";
    size_t parametersCount = 0;
    needSelection = false;
    sql += "id,";
    ++parametersCount;
    if (dirtyFlag_[1]) {
      sql += "material_type,";
      ++parametersCount;
    }
    if (dirtyFlag_[2]) {
      sql += "batch_number,";
      ++parametersCount;
    }
    if (dirtyFlag_[3]) {
      sql += "supplier_name,";
      ++parametersCount;
    }
    if (dirtyFlag_[4]) {
      sql += "in_date,";
      ++parametersCount;
    }
    if (dirtyFlag_[5]) {
      sql += "quantity,";
      ++parametersCount;
    }
    if (dirtyFlag_[6]) {
      sql += "unit,";
      ++parametersCount;
    }
    if (dirtyFlag_[7]) {
      sql += "quality_level,";
      ++parametersCount;
    }
    if (dirtyFlag_[8]) {
      sql += "storage_location,";
      ++parametersCount;
    }
    if (dirtyFlag_[9]) {
      sql += "inspection_no,";
      ++parametersCount;
    }
    if (dirtyFlag_[10]) {
      sql += "status,";
      ++parametersCount;
    }
    if (dirtyFlag_[11]) {
      sql += "operator,";
      ++parametersCount;
    }
    sql += "created_at,";
    ++parametersCount;
    if (!dirtyFlag_[12]) {
      needSelection = true;
    }
    sql += "updated_at,";
    ++parametersCount;
    if (!dirtyFlag_[13]) {
      needSelection = true;
    }
    needSelection = true;
    if (parametersCount > 0) {
      sql[sql.length() - 1] = ')';
      sql += " values (";
    } else
      sql += ") values (";

    int placeholder = 1;
    char placeholderStr[64];
    size_t n = 0;
    sql += "default,";
    if (dirtyFlag_[1]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[2]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[3]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[4]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[5]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[6]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[7]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[8]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[9]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[10]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[11]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    }
    if (dirtyFlag_[12]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    } else {
      sql += "default,";
    }
    if (dirtyFlag_[13]) {
      n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
      sql.append(placeholderStr, n);
    } else {
      sql += "default,";
    }
    if (parametersCount > 0) {
      sql.resize(sql.length() - 1);
    }
    if (needSelection) {
      sql.append(") returning *");
    } else {
      sql.append(1, ')');
    }
    LOG_TRACE << sql;
    return sql;
  }
};
} // namespace los_css_drogon
} // namespace drogon_model
