/**
 *
 *  Seedlings.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Seedlings.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::los_css_drogon;

const std::string Seedlings::Cols::_id = "\"id\"";
const std::string Seedlings::Cols::_seed_id = "\"seed_id\"";
const std::string Seedlings::Cols::_germination_rate = "\"germination_rate\"";
const std::string Seedlings::Cols::_growth_status = "\"growth_status\"";
const std::string Seedlings::Cols::_plant_date = "\"plant_date\"";
const std::string Seedlings::Cols::_start_time = "\"start_time\"";
const std::string Seedlings::Cols::_end_time = "\"end_time\"";
const std::string Seedlings::Cols::_method = "\"method\"";
const std::string Seedlings::Cols::_environment_params = "\"environment_params\"";
const std::string Seedlings::Cols::_operator = "\"operator\"";
const std::string Seedlings::Cols::_created_at = "\"created_at\"";
const std::string Seedlings::Cols::_updated_at = "\"updated_at\"";
const std::string Seedlings::primaryKeyName = "id";
const bool Seedlings::hasPrimaryKey = true;
const std::string Seedlings::tableName = "\"seedlings\"";

const std::vector<typename Seedlings::MetaData> Seedlings::metaData_ = {
    {"id", "int32_t", "integer", 4, 1, 1, 1},
    {"seed_id", "int32_t", "integer", 4, 0, 0, 1},
    {"germination_rate", "std::string", "numeric", 0, 0, 0, 0},
    {"growth_status", "std::string", "character varying", 16, 0, 0, 1},
    {"plant_date", "::trantor::Date", "date", 0, 0, 0, 1},
    {"start_time", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 0},
    {"end_time", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 0},
    {"method", "std::string", "character varying", 128, 0, 0, 0},
    {"environment_params", "std::string", "text", 0, 0, 0, 0},
    {"operator", "std::string", "character varying", 64, 0, 0, 0},
    {"created_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1},
    {"updated_at", "::trantor::Date", "timestamp without time zone", 0, 0, 0, 1}};
const std::string &Seedlings::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
Seedlings::Seedlings(const Row &r, const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["id"].isNull()) {
      id_ = std::make_shared<int32_t>(r["id"].as<int32_t>());
    }
    if (!r["seed_id"].isNull()) {
      seedId_ = std::make_shared<int32_t>(r["seed_id"].as<int32_t>());
    }
    if (!r["germination_rate"].isNull()) {
      germinationRate_ = std::make_shared<std::string>(r["germination_rate"].as<std::string>());
    }
    if (!r["growth_status"].isNull()) {
      growthStatus_ = std::make_shared<std::string>(r["growth_status"].as<std::string>());
    }
    if (!r["plant_date"].isNull()) {
      auto daysStr = r["plant_date"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      plantDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
    if (!r["start_time"].isNull()) {
      auto timeStr = r["start_time"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    if (!r["end_time"].isNull()) {
      auto timeStr = r["end_time"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    if (!r["method"].isNull()) {
      method_ = std::make_shared<std::string>(r["method"].as<std::string>());
    }
    if (!r["environment_params"].isNull()) {
      environmentParams_ = std::make_shared<std::string>(r["environment_params"].as<std::string>());
    }
    if (!r["operator"].isNull()) {
      operator_ = std::make_shared<std::string>(r["operator"].as<std::string>());
    }
    if (!r["created_at"].isNull()) {
      auto timeStr = r["created_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    if (!r["updated_at"].isNull()) {
      auto timeStr = r["updated_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 12 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      id_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      seedId_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 2;
    if (!r[index].isNull()) {
      germinationRate_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 3;
    if (!r[index].isNull()) {
      growthStatus_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 4;
    if (!r[index].isNull()) {
      auto daysStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      plantDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
    index = offset + 5;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    index = offset + 6;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    index = offset + 7;
    if (!r[index].isNull()) {
      method_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 8;
    if (!r[index].isNull()) {
      environmentParams_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 9;
    if (!r[index].isNull()) {
      operator_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 10;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
    index = offset + 11;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

Seedlings::Seedlings(const Json::Value &pJson,
                     const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 12) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      seedId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      germinationRate_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      growthStatus_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      auto daysStr = pJson[pMasqueradingVector[4]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      plantDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[5]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[6]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      method_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      environmentParams_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
    }
  }
  if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
    dirtyFlag_[9] = true;
    if (!pJson[pMasqueradingVector[9]].isNull()) {
      operator_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
    }
  }
  if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
    dirtyFlag_[10] = true;
    if (!pJson[pMasqueradingVector[10]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[10]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
    dirtyFlag_[11] = true;
    if (!pJson[pMasqueradingVector[11]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[11]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

Seedlings::Seedlings(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    dirtyFlag_[0] = true;
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("seed_id")) {
    dirtyFlag_[1] = true;
    if (!pJson["seed_id"].isNull()) {
      seedId_ = std::make_shared<int32_t>((int32_t)pJson["seed_id"].asInt64());
    }
  }
  if (pJson.isMember("germination_rate")) {
    dirtyFlag_[2] = true;
    if (!pJson["germination_rate"].isNull()) {
      germinationRate_ = std::make_shared<std::string>(pJson["germination_rate"].asString());
    }
  }
  if (pJson.isMember("growth_status")) {
    dirtyFlag_[3] = true;
    if (!pJson["growth_status"].isNull()) {
      growthStatus_ = std::make_shared<std::string>(pJson["growth_status"].asString());
    }
  }
  if (pJson.isMember("plant_date")) {
    dirtyFlag_[4] = true;
    if (!pJson["plant_date"].isNull()) {
      auto daysStr = pJson["plant_date"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      plantDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (pJson.isMember("start_time")) {
    dirtyFlag_[5] = true;
    if (!pJson["start_time"].isNull()) {
      auto timeStr = pJson["start_time"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("end_time")) {
    dirtyFlag_[6] = true;
    if (!pJson["end_time"].isNull()) {
      auto timeStr = pJson["end_time"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("method")) {
    dirtyFlag_[7] = true;
    if (!pJson["method"].isNull()) {
      method_ = std::make_shared<std::string>(pJson["method"].asString());
    }
  }
  if (pJson.isMember("environment_params")) {
    dirtyFlag_[8] = true;
    if (!pJson["environment_params"].isNull()) {
      environmentParams_ = std::make_shared<std::string>(pJson["environment_params"].asString());
    }
  }
  if (pJson.isMember("operator")) {
    dirtyFlag_[9] = true;
    if (!pJson["operator"].isNull()) {
      operator_ = std::make_shared<std::string>(pJson["operator"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[10] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[11] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void Seedlings::updateByMasqueradedJson(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 12) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      seedId_ = std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
    }
  }
  if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      germinationRate_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
    }
  }
  if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      growthStatus_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      auto daysStr = pJson[pMasqueradingVector[4]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      plantDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[5]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
    dirtyFlag_[6] = true;
    if (!pJson[pMasqueradingVector[6]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[6]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
    dirtyFlag_[7] = true;
    if (!pJson[pMasqueradingVector[7]].isNull()) {
      method_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
    }
  }
  if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
    dirtyFlag_[8] = true;
    if (!pJson[pMasqueradingVector[8]].isNull()) {
      environmentParams_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
    }
  }
  if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
    dirtyFlag_[9] = true;
    if (!pJson[pMasqueradingVector[9]].isNull()) {
      operator_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
    }
  }
  if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
    dirtyFlag_[10] = true;
    if (!pJson[pMasqueradingVector[10]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[10]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
    dirtyFlag_[11] = true;
    if (!pJson[pMasqueradingVector[11]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[11]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void Seedlings::updateByJson(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("seed_id")) {
    dirtyFlag_[1] = true;
    if (!pJson["seed_id"].isNull()) {
      seedId_ = std::make_shared<int32_t>((int32_t)pJson["seed_id"].asInt64());
    }
  }
  if (pJson.isMember("germination_rate")) {
    dirtyFlag_[2] = true;
    if (!pJson["germination_rate"].isNull()) {
      germinationRate_ = std::make_shared<std::string>(pJson["germination_rate"].asString());
    }
  }
  if (pJson.isMember("growth_status")) {
    dirtyFlag_[3] = true;
    if (!pJson["growth_status"].isNull()) {
      growthStatus_ = std::make_shared<std::string>(pJson["growth_status"].asString());
    }
  }
  if (pJson.isMember("plant_date")) {
    dirtyFlag_[4] = true;
    if (!pJson["plant_date"].isNull()) {
      auto daysStr = pJson["plant_date"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      strptime(daysStr.c_str(), "%Y-%m-%d", &stm);
      time_t t = mktime(&stm);
      plantDate_ = std::make_shared<::trantor::Date>(t * 1000000);
    }
  }
  if (pJson.isMember("start_time")) {
    dirtyFlag_[5] = true;
    if (!pJson["start_time"].isNull()) {
      auto timeStr = pJson["start_time"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        startTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("end_time")) {
    dirtyFlag_[6] = true;
    if (!pJson["end_time"].isNull()) {
      auto timeStr = pJson["end_time"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        endTime_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("method")) {
    dirtyFlag_[7] = true;
    if (!pJson["method"].isNull()) {
      method_ = std::make_shared<std::string>(pJson["method"].asString());
    }
  }
  if (pJson.isMember("environment_params")) {
    dirtyFlag_[8] = true;
    if (!pJson["environment_params"].isNull()) {
      environmentParams_ = std::make_shared<std::string>(pJson["environment_params"].asString());
    }
  }
  if (pJson.isMember("operator")) {
    dirtyFlag_[9] = true;
    if (!pJson["operator"].isNull()) {
      operator_ = std::make_shared<std::string>(pJson["operator"].asString());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[10] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
  if (pJson.isMember("updated_at")) {
    dirtyFlag_[11] = true;
    if (!pJson["updated_at"].isNull()) {
      auto timeStr = pJson["updated_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        updatedAt_ = std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

const int32_t &Seedlings::getValueOfId() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (id_)
    return *id_;
  return defaultValue;
}
const std::shared_ptr<int32_t> &Seedlings::getId() const noexcept { return id_; }
void Seedlings::setId(const int32_t &pId) noexcept {
  id_ = std::make_shared<int32_t>(pId);
  dirtyFlag_[0] = true;
}
const typename Seedlings::PrimaryKeyType &Seedlings::getPrimaryKey() const {
  assert(id_);
  return *id_;
}

const int32_t &Seedlings::getValueOfSeedId() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (seedId_)
    return *seedId_;
  return defaultValue;
}
const std::shared_ptr<int32_t> &Seedlings::getSeedId() const noexcept { return seedId_; }
void Seedlings::setSeedId(const int32_t &pSeedId) noexcept {
  seedId_ = std::make_shared<int32_t>(pSeedId);
  dirtyFlag_[1] = true;
}

const std::string &Seedlings::getValueOfGerminationRate() const noexcept {
  static const std::string defaultValue = std::string();
  if (germinationRate_)
    return *germinationRate_;
  return defaultValue;
}
const std::shared_ptr<std::string> &Seedlings::getGerminationRate() const noexcept {
  return germinationRate_;
}
void Seedlings::setGerminationRate(const std::string &pGerminationRate) noexcept {
  germinationRate_ = std::make_shared<std::string>(pGerminationRate);
  dirtyFlag_[2] = true;
}
void Seedlings::setGerminationRate(std::string &&pGerminationRate) noexcept {
  germinationRate_ = std::make_shared<std::string>(std::move(pGerminationRate));
  dirtyFlag_[2] = true;
}
void Seedlings::setGerminationRateToNull() noexcept {
  germinationRate_.reset();
  dirtyFlag_[2] = true;
}

const std::string &Seedlings::getValueOfGrowthStatus() const noexcept {
  static const std::string defaultValue = std::string();
  if (growthStatus_)
    return *growthStatus_;
  return defaultValue;
}
const std::shared_ptr<std::string> &Seedlings::getGrowthStatus() const noexcept {
  return growthStatus_;
}
void Seedlings::setGrowthStatus(const std::string &pGrowthStatus) noexcept {
  growthStatus_ = std::make_shared<std::string>(pGrowthStatus);
  dirtyFlag_[3] = true;
}
void Seedlings::setGrowthStatus(std::string &&pGrowthStatus) noexcept {
  growthStatus_ = std::make_shared<std::string>(std::move(pGrowthStatus));
  dirtyFlag_[3] = true;
}

const ::trantor::Date &Seedlings::getValueOfPlantDate() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (plantDate_)
    return *plantDate_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Seedlings::getPlantDate() const noexcept {
  return plantDate_;
}
void Seedlings::setPlantDate(const ::trantor::Date &pPlantDate) noexcept {
  plantDate_ = std::make_shared<::trantor::Date>(pPlantDate.roundDay());
  dirtyFlag_[4] = true;
}

const ::trantor::Date &Seedlings::getValueOfStartTime() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (startTime_)
    return *startTime_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Seedlings::getStartTime() const noexcept {
  return startTime_;
}
void Seedlings::setStartTime(const ::trantor::Date &pStartTime) noexcept {
  startTime_ = std::make_shared<::trantor::Date>(pStartTime);
  dirtyFlag_[5] = true;
}
void Seedlings::setStartTimeToNull() noexcept {
  startTime_.reset();
  dirtyFlag_[5] = true;
}

const ::trantor::Date &Seedlings::getValueOfEndTime() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (endTime_)
    return *endTime_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Seedlings::getEndTime() const noexcept { return endTime_; }
void Seedlings::setEndTime(const ::trantor::Date &pEndTime) noexcept {
  endTime_ = std::make_shared<::trantor::Date>(pEndTime);
  dirtyFlag_[6] = true;
}
void Seedlings::setEndTimeToNull() noexcept {
  endTime_.reset();
  dirtyFlag_[6] = true;
}

const std::string &Seedlings::getValueOfMethod() const noexcept {
  static const std::string defaultValue = std::string();
  if (method_)
    return *method_;
  return defaultValue;
}
const std::shared_ptr<std::string> &Seedlings::getMethod() const noexcept { return method_; }
void Seedlings::setMethod(const std::string &pMethod) noexcept {
  method_ = std::make_shared<std::string>(pMethod);
  dirtyFlag_[7] = true;
}
void Seedlings::setMethod(std::string &&pMethod) noexcept {
  method_ = std::make_shared<std::string>(std::move(pMethod));
  dirtyFlag_[7] = true;
}
void Seedlings::setMethodToNull() noexcept {
  method_.reset();
  dirtyFlag_[7] = true;
}

const std::string &Seedlings::getValueOfEnvironmentParams() const noexcept {
  static const std::string defaultValue = std::string();
  if (environmentParams_)
    return *environmentParams_;
  return defaultValue;
}
const std::shared_ptr<std::string> &Seedlings::getEnvironmentParams() const noexcept {
  return environmentParams_;
}
void Seedlings::setEnvironmentParams(const std::string &pEnvironmentParams) noexcept {
  environmentParams_ = std::make_shared<std::string>(pEnvironmentParams);
  dirtyFlag_[8] = true;
}
void Seedlings::setEnvironmentParams(std::string &&pEnvironmentParams) noexcept {
  environmentParams_ = std::make_shared<std::string>(std::move(pEnvironmentParams));
  dirtyFlag_[8] = true;
}
void Seedlings::setEnvironmentParamsToNull() noexcept {
  environmentParams_.reset();
  dirtyFlag_[8] = true;
}

const std::string &Seedlings::getValueOfOperator() const noexcept {
  static const std::string defaultValue = std::string();
  if (operator_)
    return *operator_;
  return defaultValue;
}
const std::shared_ptr<std::string> &Seedlings::getOperator() const noexcept { return operator_; }
void Seedlings::setOperator(const std::string &pOperator) noexcept {
  operator_ = std::make_shared<std::string>(pOperator);
  dirtyFlag_[9] = true;
}
void Seedlings::setOperator(std::string &&pOperator) noexcept {
  operator_ = std::make_shared<std::string>(std::move(pOperator));
  dirtyFlag_[9] = true;
}
void Seedlings::setOperatorToNull() noexcept {
  operator_.reset();
  dirtyFlag_[9] = true;
}

const ::trantor::Date &Seedlings::getValueOfCreatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (createdAt_)
    return *createdAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Seedlings::getCreatedAt() const noexcept {
  return createdAt_;
}
void Seedlings::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept {
  createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
  dirtyFlag_[10] = true;
}

const ::trantor::Date &Seedlings::getValueOfUpdatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (updatedAt_)
    return *updatedAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Seedlings::getUpdatedAt() const noexcept {
  return updatedAt_;
}
void Seedlings::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept {
  updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
  dirtyFlag_[11] = true;
}

void Seedlings::updateId(const uint64_t id) {}

const std::vector<std::string> &Seedlings::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {
      "seed_id", "germination_rate",   "growth_status", "plant_date", "start_time", "end_time",
      "method",  "environment_params", "operator",      "created_at", "updated_at"};
  return inCols;
}

void Seedlings::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getSeedId()) {
      binder << getValueOfSeedId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getGerminationRate()) {
      binder << getValueOfGerminationRate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getGrowthStatus()) {
      binder << getValueOfGrowthStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getPlantDate()) {
      binder << getValueOfPlantDate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getStartTime()) {
      binder << getValueOfStartTime();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getEndTime()) {
      binder << getValueOfEndTime();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getMethod()) {
      binder << getValueOfMethod();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getEnvironmentParams()) {
      binder << getValueOfEnvironmentParams();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[9]) {
    if (getOperator()) {
      binder << getValueOfOperator();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[10]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[11]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> Seedlings::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  if (dirtyFlag_[2]) {
    ret.push_back(getColumnName(2));
  }
  if (dirtyFlag_[3]) {
    ret.push_back(getColumnName(3));
  }
  if (dirtyFlag_[4]) {
    ret.push_back(getColumnName(4));
  }
  if (dirtyFlag_[5]) {
    ret.push_back(getColumnName(5));
  }
  if (dirtyFlag_[6]) {
    ret.push_back(getColumnName(6));
  }
  if (dirtyFlag_[7]) {
    ret.push_back(getColumnName(7));
  }
  if (dirtyFlag_[8]) {
    ret.push_back(getColumnName(8));
  }
  if (dirtyFlag_[9]) {
    ret.push_back(getColumnName(9));
  }
  if (dirtyFlag_[10]) {
    ret.push_back(getColumnName(10));
  }
  if (dirtyFlag_[11]) {
    ret.push_back(getColumnName(11));
  }
  return ret;
}

void Seedlings::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getSeedId()) {
      binder << getValueOfSeedId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getGerminationRate()) {
      binder << getValueOfGerminationRate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getGrowthStatus()) {
      binder << getValueOfGrowthStatus();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getPlantDate()) {
      binder << getValueOfPlantDate();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getStartTime()) {
      binder << getValueOfStartTime();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[6]) {
    if (getEndTime()) {
      binder << getValueOfEndTime();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[7]) {
    if (getMethod()) {
      binder << getValueOfMethod();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[8]) {
    if (getEnvironmentParams()) {
      binder << getValueOfEnvironmentParams();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[9]) {
    if (getOperator()) {
      binder << getValueOfOperator();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[10]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[11]) {
    if (getUpdatedAt()) {
      binder << getValueOfUpdatedAt();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value Seedlings::toJson() const {
  Json::Value ret;
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getSeedId()) {
    ret["seed_id"] = getValueOfSeedId();
  } else {
    ret["seed_id"] = Json::Value();
  }
  if (getGerminationRate()) {
    ret["germination_rate"] = getValueOfGerminationRate();
  } else {
    ret["germination_rate"] = Json::Value();
  }
  if (getGrowthStatus()) {
    ret["growth_status"] = getValueOfGrowthStatus();
  } else {
    ret["growth_status"] = Json::Value();
  }
  if (getPlantDate()) {
    ret["plant_date"] = getPlantDate()->toDbStringLocal();
  } else {
    ret["plant_date"] = Json::Value();
  }
  if (getStartTime()) {
    ret["start_time"] = getStartTime()->toDbStringLocal();
  } else {
    ret["start_time"] = Json::Value();
  }
  if (getEndTime()) {
    ret["end_time"] = getEndTime()->toDbStringLocal();
  } else {
    ret["end_time"] = Json::Value();
  }
  if (getMethod()) {
    ret["method"] = getValueOfMethod();
  } else {
    ret["method"] = Json::Value();
  }
  if (getEnvironmentParams()) {
    ret["environment_params"] = getValueOfEnvironmentParams();
  } else {
    ret["environment_params"] = Json::Value();
  }
  if (getOperator()) {
    ret["operator"] = getValueOfOperator();
  } else {
    ret["operator"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

Json::Value
Seedlings::toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 12) {
    if (!pMasqueradingVector[0].empty()) {
      if (getId()) {
        ret[pMasqueradingVector[0]] = getValueOfId();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getSeedId()) {
        ret[pMasqueradingVector[1]] = getValueOfSeedId();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (getGerminationRate()) {
        ret[pMasqueradingVector[2]] = getValueOfGerminationRate();
      } else {
        ret[pMasqueradingVector[2]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (getGrowthStatus()) {
        ret[pMasqueradingVector[3]] = getValueOfGrowthStatus();
      } else {
        ret[pMasqueradingVector[3]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (getPlantDate()) {
        ret[pMasqueradingVector[4]] = getPlantDate()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[4]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (getStartTime()) {
        ret[pMasqueradingVector[5]] = getStartTime()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[5]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (getEndTime()) {
        ret[pMasqueradingVector[6]] = getEndTime()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[6]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (getMethod()) {
        ret[pMasqueradingVector[7]] = getValueOfMethod();
      } else {
        ret[pMasqueradingVector[7]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (getEnvironmentParams()) {
        ret[pMasqueradingVector[8]] = getValueOfEnvironmentParams();
      } else {
        ret[pMasqueradingVector[8]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[9].empty()) {
      if (getOperator()) {
        ret[pMasqueradingVector[9]] = getValueOfOperator();
      } else {
        ret[pMasqueradingVector[9]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[10].empty()) {
      if (getCreatedAt()) {
        ret[pMasqueradingVector[10]] = getCreatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[10]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[11].empty()) {
      if (getUpdatedAt()) {
        ret[pMasqueradingVector[11]] = getUpdatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[11]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getId()) {
    ret["id"] = getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getSeedId()) {
    ret["seed_id"] = getValueOfSeedId();
  } else {
    ret["seed_id"] = Json::Value();
  }
  if (getGerminationRate()) {
    ret["germination_rate"] = getValueOfGerminationRate();
  } else {
    ret["germination_rate"] = Json::Value();
  }
  if (getGrowthStatus()) {
    ret["growth_status"] = getValueOfGrowthStatus();
  } else {
    ret["growth_status"] = Json::Value();
  }
  if (getPlantDate()) {
    ret["plant_date"] = getPlantDate()->toDbStringLocal();
  } else {
    ret["plant_date"] = Json::Value();
  }
  if (getStartTime()) {
    ret["start_time"] = getStartTime()->toDbStringLocal();
  } else {
    ret["start_time"] = Json::Value();
  }
  if (getEndTime()) {
    ret["end_time"] = getEndTime()->toDbStringLocal();
  } else {
    ret["end_time"] = Json::Value();
  }
  if (getMethod()) {
    ret["method"] = getValueOfMethod();
  } else {
    ret["method"] = Json::Value();
  }
  if (getEnvironmentParams()) {
    ret["environment_params"] = getValueOfEnvironmentParams();
  } else {
    ret["environment_params"] = Json::Value();
  }
  if (getOperator()) {
    ret["operator"] = getValueOfOperator();
  } else {
    ret["operator"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  if (getUpdatedAt()) {
    ret["updated_at"] = getUpdatedAt()->toDbStringLocal();
  } else {
    ret["updated_at"] = Json::Value();
  }
  return ret;
}

bool Seedlings::validateJsonForCreation(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, true))
      return false;
  }
  if (pJson.isMember("seed_id")) {
    if (!validJsonOfField(1, "seed_id", pJson["seed_id"], err, true))
      return false;
  } else {
    err = "The seed_id column cannot be null";
    return false;
  }
  if (pJson.isMember("germination_rate")) {
    if (!validJsonOfField(2, "germination_rate", pJson["germination_rate"], err, true))
      return false;
  }
  if (pJson.isMember("growth_status")) {
    if (!validJsonOfField(3, "growth_status", pJson["growth_status"], err, true))
      return false;
  } else {
    err = "The growth_status column cannot be null";
    return false;
  }
  if (pJson.isMember("plant_date")) {
    if (!validJsonOfField(4, "plant_date", pJson["plant_date"], err, true))
      return false;
  } else {
    err = "The plant_date column cannot be null";
    return false;
  }
  if (pJson.isMember("start_time")) {
    if (!validJsonOfField(5, "start_time", pJson["start_time"], err, true))
      return false;
  }
  if (pJson.isMember("end_time")) {
    if (!validJsonOfField(6, "end_time", pJson["end_time"], err, true))
      return false;
  }
  if (pJson.isMember("method")) {
    if (!validJsonOfField(7, "method", pJson["method"], err, true))
      return false;
  }
  if (pJson.isMember("environment_params")) {
    if (!validJsonOfField(8, "environment_params", pJson["environment_params"], err, true))
      return false;
  }
  if (pJson.isMember("operator")) {
    if (!validJsonOfField(9, "operator", pJson["operator"], err, true))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(10, "created_at", pJson["created_at"], err, true))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(11, "updated_at", pJson["updated_at"], err, true))
      return false;
  }
  return true;
}
bool Seedlings::validateMasqueradedJsonForCreation(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 12) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[1] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (pJson.isMember(pMasqueradingVector[2])) {
        if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (pJson.isMember(pMasqueradingVector[3])) {
        if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[3] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (pJson.isMember(pMasqueradingVector[4])) {
        if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[4] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (pJson.isMember(pMasqueradingVector[5])) {
        if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[6].empty()) {
      if (pJson.isMember(pMasqueradingVector[6])) {
        if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[7].empty()) {
      if (pJson.isMember(pMasqueradingVector[7])) {
        if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[8].empty()) {
      if (pJson.isMember(pMasqueradingVector[8])) {
        if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[9].empty()) {
      if (pJson.isMember(pMasqueradingVector[9])) {
        if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[10].empty()) {
      if (pJson.isMember(pMasqueradingVector[10])) {
        if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err,
                              true))
          return false;
      }
    }
    if (!pMasqueradingVector[11].empty()) {
      if (pJson.isMember(pMasqueradingVector[11])) {
        if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err,
                              true))
          return false;
      }
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool Seedlings::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, false))
      return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("seed_id")) {
    if (!validJsonOfField(1, "seed_id", pJson["seed_id"], err, false))
      return false;
  }
  if (pJson.isMember("germination_rate")) {
    if (!validJsonOfField(2, "germination_rate", pJson["germination_rate"], err, false))
      return false;
  }
  if (pJson.isMember("growth_status")) {
    if (!validJsonOfField(3, "growth_status", pJson["growth_status"], err, false))
      return false;
  }
  if (pJson.isMember("plant_date")) {
    if (!validJsonOfField(4, "plant_date", pJson["plant_date"], err, false))
      return false;
  }
  if (pJson.isMember("start_time")) {
    if (!validJsonOfField(5, "start_time", pJson["start_time"], err, false))
      return false;
  }
  if (pJson.isMember("end_time")) {
    if (!validJsonOfField(6, "end_time", pJson["end_time"], err, false))
      return false;
  }
  if (pJson.isMember("method")) {
    if (!validJsonOfField(7, "method", pJson["method"], err, false))
      return false;
  }
  if (pJson.isMember("environment_params")) {
    if (!validJsonOfField(8, "environment_params", pJson["environment_params"], err, false))
      return false;
  }
  if (pJson.isMember("operator")) {
    if (!validJsonOfField(9, "operator", pJson["operator"], err, false))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(10, "created_at", pJson["created_at"], err, false))
      return false;
  }
  if (pJson.isMember("updated_at")) {
    if (!validJsonOfField(11, "updated_at", pJson["updated_at"], err, false))
      return false;
  }
  return true;
}
bool Seedlings::validateMasqueradedJsonForUpdate(
    const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector,
    std::string &err) {
  if (pMasqueradingVector.size() != 12) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err = "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
        return false;
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
      if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
        return false;
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
      if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
        return false;
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
      if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
        return false;
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
      if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
        return false;
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
      if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
        return false;
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
      if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
        return false;
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
      if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
        return false;
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
      if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
        return false;
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
      if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err,
                            false))
        return false;
    }
    if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
      if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err,
                            false))
        return false;
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool Seedlings::validJsonOfField(size_t index, const std::string &fieldName,
                                 const Json::Value &pJson, std::string &err, bool isForCreation) {
  switch (index) {
  case 0:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (isForCreation) {
      err = "The automatic primary key cannot be set";
      return false;
    }
    if (!pJson.isInt()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 1:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isInt()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 2:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 3:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 16) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 16)";
      return false;
    }

    break;
  case 4:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 5:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 6:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 7:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 128) {
      err =
          "String length exceeds limit for the " + fieldName + " field (the maximum value is 128)";
      return false;
    }

    break;
  case 8:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 9:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    if (pJson.isString() && std::strlen(pJson.asCString()) > 64) {
      err = "String length exceeds limit for the " + fieldName + " field (the maximum value is 64)";
      return false;
    }

    break;
  case 10:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 11:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  default:
    err = "Internal error in the server";
    return false;
  }
  return true;
}
